# Coursework 1 

### PLAGIARISM/COLLUSION DECLARATION

 

Coursework submitted for assessment must be the original work of you and your group. Assignments are subjected to regular checks for plagiarism and/or collusion. Plagiarism is the presentation of another person’s thoughts or words (those outside your group) as if they were your own. Collusion involves obtaining help from someone outside your group to complete your work. In preparing your coursework, you should not seek help, or copy from any other person or source, including the

Internet, without proper and explicit acknowledgement.

 

There is a procedure in place for you to declare individual contributions within your group for courswork. You must declare the contributions fairly and accurately.

 

You must not disclose your solutions or insights related to coursework with anyone else, including future students or the Internet.

 

By acknowledging the the statements above, you are declaring that both this and all subsequent pieces of coursework are, and will remain, the original work of you and your group.

 

* Submissions will not be accepted without the aforementioned declaration.

 

* Members of a group are deemed to have collective responsibility for the integrity for work submitted and are liable for any penalty imposed, proportionate to their contributions.

In [1]:
import Pkg
Pkg.add("DSP")
Pkg.add("FFTW")
Pkg.add("LinearOperators")
Pkg.add("IterativeSolvers")
Pkg.add("LinearMaps")

using JLD2,FileIO
using LinearAlgebra
using LinearMaps
using LinearOperators
using IterativeSolvers


   Resolving package versions...


  No Changes to `C:\Users\honan\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\honan\.julia\environments\v1.9\Manifest.toml`


   Resolving package versions...
  No Changes to `C:\Users\honan\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\honan\.julia\environments\v1.9\Manifest.toml`


   Resolving package versions...


  No Changes to `C:\Users\honan\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\honan\.julia\environments\v1.9\Manifest.toml`


   Resolving package versions...


  No Changes to `C:\Users\honan\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\honan\.julia\environments\v1.9\Manifest.toml`

   Resolving package versions...


  No Changes to `C:\Users\honan\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\honan\.julia\environments\v1.9\Manifest.toml`


In [2]:
# Run this code before you start doing the coursework

Base.@kwdef mutable struct CourseWork_1
    CID::Int
    Plagiarism_declare::Union{Missing,Bool}
    Demo_willing::Union{Missing,Bool}
    
    # 4.1. Trace and Inner Product of Matrices
    
    Q4_1_1_data_m::Int
    Q4_1_1_data_n::Int
    
    Q4_1_1_a_ans_rows::Union{Missing,Int}
    Q4_1_1_a_ans_columns::Union{Missing,Int}
    Q4_1_1_b_ans_rows::Union{Missing,Int}
    Q4_1_1_b_ans_columns::Union{Missing,Int}
    Q4_1_1_c_ans::Union{Missing,Bool}
    
    Q4_1_2_ans::Union{Missing,Bool}
    
    Q4_1_3_data_k::Int
    Q4_1_3_data_l::Int
    Q4_1_3_data_m::Int
    Q4_1_3_data_n::Int

    Q4_1_3_a_ans_Urows::Union{Missing,Int}
    Q4_1_3_a_ans_Ucolumns::Union{Missing,Int}
    Q4_1_3_a_ans_Vrows::Union{Missing,Int}
    Q4_1_3_a_ans_Vcolumns::Union{Missing,Int}
    Q4_1_3_b_ans::Union{Missing,Bool}
    
    # 4.2. The Matrix of the Linear Map
    
    Q4_2_1_ans::Union{Missing,Bool}
    
    # 4.3. Adjoint Operator
    
    Q4_3_1_data_n::Int
    Q4_3_1_data_Omega::Vector{Int}
    Q4_3_1_data_x::Vector
   
    Q4_3_1_a_ans_Operator::Union{Missing,Matrix}
    Q4_3_1_a_ans_AdjointOperator::Union{Missing,Matrix}
    Q4_3_1_b_ans_y::Union{Missing,Vector}
    Q4_3_1_c_ans_z::Union{Missing,Vector}
    
    
    Q4_3_2_data_p::Int
    Q4_3_2_data_q::Int
    Q4_3_2_data_x::Vector
    
    Q4_3_2_a_ans_Operator::Union{Missing,Matrix}
    Q4_3_2_a_ans_AdjointOperator::Union{Missing,Matrix}
    Q4_3_2_b_ans_H::Union{Missing,Matrix}
    Q4_3_2_c_ans_z::Union{Missing,Vector}
    Q4_3_2_d_ans::Union{Missing,Vector}
    
    Q4_3_3_data_h::Vector
    Q4_3_3_data_x::Vector
    
    Q4_3_3_a_ans_Operator::Union{Missing,Matrix}
    Q4_3_3_a_ans_AdjointOperator::Union{Missing,Matrix}
    Q4_3_3_b_ans_y::Union{Missing,Vector}
    Q4_3_3_c_ans_z::Union{Missing,Vector}
    
    Q4_3_4_data_h::Vector
    Q4_3_4_data_x::Vector
    
    Q4_3_4_a_ans_Operator::Union{Missing,Matrix}
    Q4_3_4_a_ans_AdjointOperator::Union{Missing,Matrix}
    Q4_3_4_b_ans_y::Union{Missing,Vector}
    Q4_3_4_c_ans_z::Union{Missing,Vector}
    
    Q4_3_5_data_X::Matrix{Float64}
    Q4_3_5_data_Omega::Matrix
    
    Q4_3_5_a_ans_O1::Union{Missing,Matrix}
    Q4_3_5_a_ans_O2::Union{Missing,Matrix}
    Q4_3_5_a_ans_O3::Union{Missing,Vector}
    Q4_3_5_b_ans_O1::Union{Missing,Matrix}
    Q4_3_5_b_ans_O2::Union{Missing,Matrix}
    Q4_3_5_b_ans_O3::Union{Missing,Matrix}
    
    # 5.1. The Netflix Problem
    
    Q5_1_data_y::Vector
    Q5_1_data_Omega::Matrix
    Q5_1_data_Uini::Matrix{Float64}
    
    Q5_1_a_ans_V::Union{Missing,Matrix}
    Q5_1_b_ans_U::Union{Missing,Matrix}
    Q5_1_c_ans_U::Union{Missing,Matrix}
    Q5_1_c_ans_V::Union{Missing,Matrix}
    
    
    # 5.2. Estimation Accuracy
    
    Q5_2_data_A::Matrix{Float64}
    
    Q5_2_a_ans_w::Union{Missing,Vector}
    Q5_2_a_ans_err::Union{Missing,Float64}
    Q5_2_b_ans_w::Union{Missing,Vector}
    Q5_2_b_ans_err::Union{Missing,Float64}
    Q5_2_c_ans_err::Union{Missing,Float64}
    
    # 5.3. LS Recovery from Convolution
    
    Q5_3_data_y::Vector
    Q5_3_data_h::Vector
    Q5_3_data_Omega::Vector
    Q5_3_data_n::Int
    Q5_3_data_alpha::Float64
    Q5_3_data_u::Vector
    Q5_3_data_v::Vector
    
    Q5_3_1_a_ans_A::Union{Missing,Matrix}
    Q5_3_1_a_ans_b::Union{Missing,Vector}
    Q5_3_1_b_ans_x::Union{Missing,Vector}
    Q5_3_2_a_ans_uAv::Union{Missing,Float64}
    Q5_3_2_a_ans_bu::Union{Missing,Float64}
    Q5_3_2_b_ans_x::Union{Missing,Vector}
    
    # 5.4. LS Recovery for MRI
    
    Q5_4_data_X::Matrix
    Q5_4_data_Omega::Matrix
    Q5_4_data_alpha::Float64
    Q5_4_data_u::Vector{Float64}
    Q5_4_data_v::Vector{Float64}
    Q5_4_data_z::Vector{Float64}
    
    Q5_4_1_a_ans_y::Union{Missing,Vector}
    Q5_4_1_b_ans_uAv::Union{Missing,ComplexF64}
    Q5_4_1_b_ans_bz::Union{Missing,ComplexF64}
    Q5_4_1_c_ans_X_hat::Union{Missing,Matrix}
end

CourseWork_1

In [3]:
# Download and upload data from JLD file, refer to https://juliaio.github.io/JLD2.jl/dev/


# Example

A = JLD2.load("Chin Young Anson, Hon1260366StudentFile.jld2");

A = A[ "CourseWork_1" ];

A.Demo_willing = true;

 
jldopen("Chin Young Anson, Hon1260366StudentFile.jld2", "w") do file

   write(file, "CourseWork_1", A)

end

In [4]:

show(A.Q5_2_a_ans_w)

missing

## 4.1. Trace and Inner Product of Matrices


### 1. (a)

In [5]:
# save your answers in Q4_1_1_a_ans_rows, Q4_1_1_a_ans_columns
A.Q4_1_1_a_ans_rows = A.Q4_1_1_data_m
A.Q4_1_1_a_ans_columns = A.Q4_1_1_data_m

22

### 1. (b)

In [6]:
# save your answers in Q4_1_1_b_ans_rows, Q4_1_1_b_ans_columns
A.Q4_1_1_b_ans_rows = A.Q4_1_1_data_n
A.Q4_1_1_b_ans_columns = A.Q4_1_1_data_n

96

In [7]:
A.Q4_1_1_b_ans_columns

96

### 1. (c)

In [8]:
# save your answers in Q4_1_1_c_ans
A.Q4_1_1_c_ans = true

true

### 2

In [9]:
A.Q4_1_2_ans = true

true

### 3. (a)

In [10]:
A.Q4_1_3_a_ans_Urows = A.Q4_1_3_data_m
A.Q4_1_3_a_ans_Ucolumns = A.Q4_1_3_data_k
A.Q4_1_3_a_ans_Vrows = A.Q4_1_3_data_n
A.Q4_1_3_a_ans_Vcolumns = A.Q4_1_3_data_l

69

In [11]:
print("Q4_1_3_data_k = " , A.Q4_1_3_data_k, "\n")
print("Q4_1_3_data_l = " , A.Q4_1_3_data_l, "\n")
print("Q4_1_3_data_m = " , A.Q4_1_3_data_m, "\n")
print("Q4_1_3_data_n = " , A.Q4_1_3_data_n, "\n")

Q4_1_3_data_k = 72
Q4_1_3_data_l = 69
Q4_1_3_data_m = 73
Q4_1_3_data_n = 34


### 3. (b)

In [12]:
A.Q4_1_3_b_ans = true

true

## 4.2. The Matrix of the Linear Map


### 1

In [13]:
A.Q4_2_1_ans = true

true

## 4.3. Adjoint Operator

### 1.(a)

In [14]:
function SubSampl_Op(n,Omega)
    #build an m = Omega.length * n matrix, call it M, which is the linear map
    m = zeros(length(Omega),n)
    #fill in ones in matrix, where M[i,Omega[i]] = 1
    for i in 1:length(Omega)
        m[i,Omega[i]] = 1
    end
    #return the matrix
    return m, transpose(m)
end

A.Q4_3_1_a_ans_Operator , A.Q4_3_1_a_ans_AdjointOperator = 
SubSampl_Op(
    A.Q4_3_1_data_n,
    A.Q4_3_1_data_Omega
    )

([0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 1.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 1.0; 0.0 0.0 … 0.0 0.0])

In [15]:
#print("Q4_3_1_data_n = " , A["CourseWork_1"].Q4_3_1_data_n, "\n")
#print("Q4_3_1_data_Omega = " , A["CourseWork_1"].Q4_3_1_data_Omega, "\n")
#print("Q4_3_1_data_x = " , A["CourseWork_1"].Q4_3_1_data_x, "\n")
#test:
#y = A["CourseWork_1"].Q4_3_1_a_ans_Operator*A["CourseWork_1"].Q4_3_1_data_x
#print(y)

In [16]:
#test:
A.Q4_3_1_a_ans_Operator*A.Q4_3_1_data_x

35-element Vector{Float64}:
 -0.7120263375637099
 -0.3350809296111196
 -0.10569899740463622
 -0.7025129961596984
  1.2830149847033867
 -0.7176318751925367
 -1.1166279172153384
  1.3518746859672155
 -1.2785399384565972
  0.5559971550784112
  ⋮
 -0.2225617304775508
 -0.2588815665080058
 -1.0776861194782485
  0.7674149491198085
 -0.8271655141893217
  0.0850861512165227
  0.8653510720115296
 -1.3106676748148585
  0.050138419750105315

### 1.(b)

In [17]:
function Subsample(x,Omega)
    output = zeros(length(Omega))
    #loop through Omega and fill in y with x[omega[i]]
    for i in 1:length(Omega)
        output[i] = x[Omega[i]]
    end 
    return output
end


#run the function to assign to answer
#Q4_3_1_b_ans_y::Union{Missing,Vector}
A.Q4_3_1_b_ans_y = Subsample(A.Q4_3_1_data_x,A.Q4_3_1_data_Omega)

35-element Vector{Float64}:
 -0.7120263375637099
 -0.3350809296111196
 -0.10569899740463622
 -0.7025129961596984
  1.2830149847033867
 -0.7176318751925367
 -1.1166279172153384
  1.3518746859672155
 -1.2785399384565972
  0.5559971550784112
  ⋮
 -0.2225617304775508
 -0.2588815665080058
 -1.0776861194782485
  0.7674149491198085
 -0.8271655141893217
  0.0850861512165227
  0.8653510720115296
 -1.3106676748148585
  0.050138419750105315

### 1.(c)

In [18]:
function Subsample_adj(y,Omega,n)
    z = zeros(n)
    for i in 1:length(Omega)
        z[Omega[i]] = y[i]
    end
    return z
end

#test:
A.Q4_3_1_c_ans_z = Subsample_adj(A.Q4_3_1_b_ans_y,A.Q4_3_1_data_Omega,A.Q4_3_1_data_n)
#Q4_3_1_c_ans_z::Union{Missing,Vector}



90-element Vector{Float64}:
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
 -0.7120263375637099
 -0.3350809296111196
  0.0
  0.0
  ⋮
  0.0
  0.0
  0.0850861512165227
  0.8653510720115296
  0.0
  0.0
 -1.3106676748148585
  0.050138419750105315
  0.0

### 2.(a)

In [19]:
function Q4_3_2_a_ans(p, q)

    output = zeros(p*q,p+q-1)
    output_adj = zeros(p+q-1,p*q)
    m = 1

    for i in 1:q
        for j in 1:p
            output[m,i+j-1] = 1 #fill in ones into operator accordingly
            m+=1 
        end
    end

    return output, transpose(output)
end


#assign to answer
A.Q4_3_2_a_ans_Operator, A.Q4_3_2_a_ans_AdjointOperator = 
Q4_3_2_a_ans(
    A.Q4_3_2_data_p,
    A.Q4_3_2_data_q
)
#Q4_3_2_a_ans_AdjointOperator::Union{Missing,Matrix}


([1.0 0.0 … 0.0 0.0; 0.0 1.0 … 0.0 0.0; … ; 0.0 0.0 … 1.0 0.0; 0.0 0.0 … 0.0 1.0], [1.0 0.0 … 0.0 0.0; 0.0 1.0 … 0.0 0.0; … ; 0.0 0.0 … 1.0 0.0; 0.0 0.0 … 0.0 1.0])

In [20]:
#test the operator
vect = A.Q4_3_2_a_ans_Operator*A.Q4_3_2_data_x
m = vect[:,:]
reshape(m,63,93)
#looking good

63×93 Matrix{Float64}:
 -0.703016    0.767841    0.391556   …  -0.0652388  -1.13269   -1.02731
  0.767841    0.391556    2.06689       -1.13269    -1.02731   -0.869131
  0.391556    2.06689    -0.381678      -1.02731    -0.869131   2.03767
  2.06689    -0.381678   -0.39857       -0.869131    2.03767    0.231659
 -0.381678   -0.39857     0.479802       2.03767     0.231659   0.779107
 -0.39857     0.479802   -2.06458    …   0.231659    0.779107  -2.85532
  0.479802   -2.06458     0.311218       0.779107   -2.85532    1.61624
 -2.06458     0.311218   -1.60753       -2.85532     1.61624    0.888969
  0.311218   -1.60753    -0.408357       1.61624     0.888969  -0.488583
 -1.60753    -0.408357    0.151226       0.888969   -0.488583   0.645388
  ⋮                                  ⋱   ⋮                     
  2.68556    -0.721596    1.71901       -0.102503    0.968977  -0.629898
 -0.721596    1.71901    -1.97256    …   0.968977   -0.629898  -0.592585
  1.71901    -1.97256    -0.299998      -

In [21]:
#make vector x first
vect_x = A.Q4_3_2_data_x

#make a vector y for testing
vect_y = vect_x

#transform them individually
vect_y_transform = A.Q4_3_2_a_ans_Operator*vect_y
vect_x_transform = A.Q4_3_2_a_ans_Operator*vect_x

#take inner product
transpose(vect_x_transform)*vect_y_transform

#6850.4006511862335

6850.4006511862335

In [22]:
#now, test the original vector x times adjoint transform of transformed y
vect_y_adj = A.Q4_3_2_a_ans_AdjointOperator*vect_y_transform
vect_y_adj

#6850.4006511862335

155-element Vector{Float64}:
  -0.7030158807938457
   1.535682022686232
   1.1746691120748582
   8.267564946627187
  -1.9083909219122193
  -2.3914211218080244
   3.3586156917812717
 -16.51667312175439
   2.800960902327336
 -16.07525425093906
   ⋮
  -5.6690849450876035
  -4.740682869063179
  -6.677637220012744
  10.0215198055596
  -7.574875373889979
   8.414598040735248
  -0.6273441973984029
   3.0707426937953914
  -2.1585486519157375

### 2.(b)

In [23]:
function Q4_3_2_b(p,q,x)
    H = zeros(p*q,1)
    idx = 1
    for i in 1:q
      for j in 1:p
        H[idx] = x[i+j-1]
        idx += 1 
      end
    end
    return reshape(H,p,q)
end

#Q4_3_2_b_ans_H::Union{Missing,Matrix}
A.Q4_3_2_b_ans_H = Q4_3_2_b(
    A.Q4_3_2_data_p,
    A.Q4_3_2_data_q,
    A.Q4_3_2_data_x
)



63×93 Matrix{Float64}:
 -0.703016    0.767841    0.391556   …  -0.0652388  -1.13269   -1.02731
  0.767841    0.391556    2.06689       -1.13269    -1.02731   -0.869131
  0.391556    2.06689    -0.381678      -1.02731    -0.869131   2.03767
  2.06689    -0.381678   -0.39857       -0.869131    2.03767    0.231659
 -0.381678   -0.39857     0.479802       2.03767     0.231659   0.779107
 -0.39857     0.479802   -2.06458    …   0.231659    0.779107  -2.85532
  0.479802   -2.06458     0.311218       0.779107   -2.85532    1.61624
 -2.06458     0.311218   -1.60753       -2.85532     1.61624    0.888969
  0.311218   -1.60753    -0.408357       1.61624     0.888969  -0.488583
 -1.60753    -0.408357    0.151226       0.888969   -0.488583   0.645388
  ⋮                                  ⋱   ⋮                     
  2.68556    -0.721596    1.71901       -0.102503    0.968977  -0.629898
 -0.721596    1.71901    -1.97256    …   0.968977   -0.629898  -0.592585
  1.71901    -1.97256    -0.299998      -

### 2.(c)

In [24]:
function Q4_3_2_c(p,q,H)
    
    output = zeros(p+q-1)
    minpq = min(p,q)


    #collect each term in matrixx Q4_3_2_b_ans_H
    v = zeros(p+q-1)
    for i in 1:p
        v[i] = H[i,1]
    end
    for i in 1:q-1
        v[p+i] = H[p,i+1]
    end

    help = zeros(p+q-1)
    for i in 1:minpq
        help[i] = i
        help[p+q-i] = i
    end
    for i in minpq+1:p+q-minpq
        help[i] = minpq
    end

    j = 0
    for i in 1:p+q-1
        output[i] = v[i] * help[i]
    end


    return output
end

A.Q4_3_2_c_ans_z = Q4_3_2_c(
    A.Q4_3_2_data_p,
    A.Q4_3_2_data_q,
    A.Q4_3_2_b_ans_H
)

#Q4_3_2_c_ans_z::Union{Missing,Vector}


155-element Vector{Float64}:
  -0.7030158807938457
   1.535682022686232
   1.1746691120748582
   8.267564946627187
  -1.9083909219122193
  -2.3914211218080244
   3.3586156917812717
 -16.51667312175439
   2.800960902327336
 -16.075254250939064
   ⋮
  -5.6690849450876035
  -4.740682869063179
  -6.677637220012743
  10.021519805559603
  -7.574875373889979
   8.414598040735248
  -0.6273441973984029
   3.0707426937953914
  -2.1585486519157375

In [25]:
A.Q4_3_2_c_ans_z - vect_y_adj

155-element Vector{Float64}:
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
 -3.552713678800501e-15
  ⋮
  0.0
  0.0
  8.881784197001252e-16
  1.7763568394002505e-15
  0.0
  0.0
  0.0
  0.0
  0.0

### 2.(d)

In [26]:
A.Q4_3_2_d_ans = A.Q4_3_2_c_ans_z ./ A.Q4_3_2_data_x



155-element Vector{Float64}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0
  ⋮
  9.0
  8.0
  7.0
  6.000000000000001
  5.0
  4.0
  3.0000000000000004
  2.0
  1.0

### 3.(a)

In [27]:
function Convolution(x,h)
    n=length(x)
    m=length(h)
    C_h=zeros(n+m-1,n)
    for i in 1:(n+m-1)
        for j in 1:n
            if i-j>=0 && i-j<m
                C_h[i,j]=h[i-j+1]
            end
        end
    end
    C_star=transpose(C_h)
    return C_h,C_star
end
A.Q4_3_3_a_ans_Operator,A.Q4_3_3_a_ans_AdjointOperator = Convolution(A.Q4_3_3_data_x,A.Q4_3_3_data_h)

([1.3824927555505953 0.0 … 0.0 0.0; -0.5103166046164548 1.3824927555505953 … 0.0 0.0; … ; 0.0 0.0 … -0.5954076268360049 1.4418340630763695; 0.0 0.0 … 0.0 -0.5954076268360049], [1.3824927555505953 -0.5103166046164548 … 0.0 0.0; 0.0 1.3824927555505953 … 0.0 0.0; … ; 0.0 0.0 … -0.5954076268360049 0.0; 0.0 0.0 … 1.4418340630763695 -0.5954076268360049])

### 3.(b)

In [28]:
function find3by(x,h)
    n=length(x)
    m=length(h)
    y=zeros(n+m-1)
    for t in 1:n+m-1
        for tau in max(1,t+1-n):min(t,m,n)
            y[t]+=x[t+1-tau]*h[tau]
        end
    end
    return y
end
A.Q4_3_3_b_ans_y=find3by(A.Q4_3_3_data_x,A.Q4_3_3_data_h)

30-element Vector{Float64}:
  0.34718847379108875
 -1.2037466115407542
  1.2143237704132197
 -0.8471708509259193
  0.21167344856642728
  3.2408012713515277
  0.6000918278214773
  0.5409199682492275
  2.3811466674810604
 -2.2237756862166327
  ⋮
 -0.022969189555171243
 -2.9153057871158228
  1.1226247740081816
 -2.280458054916075
  0.8419779301022432
 -3.2712458940538798
  1.8311920634633472
 -0.5352228267139241
 -0.04900675846325167

### 3.(c)

In [29]:
function find3cz(y,h)
    m=length(h)
    n=length(y)-m+1
    z=zeros(n)
    for t in 1:n
        for tau in 1:m
            z[t]+=y[t+tau-1]*h[tau]
        end
    end
    return z
end
Z_free = A.Q4_3_3_c_ans_z=find3cz(A.Q4_3_3_b_ans_y,A.Q4_3_3_data_h)

17-element Vector{Float64}:
  -0.6694613947132696
  -6.8800835916907275
   6.003516101366196
   7.916746540405512
 -10.370132093904317
  32.10665575363984
   5.597247955218237
   2.0833467022322765
   0.9979008161259771
  10.99806129575536
 -19.316733749680562
  21.927495498115704
  -6.660649428009175
   8.339631950670569
 -18.033903348795953
  20.5098866386054
 -17.519123657614617

### 4.(a)

In [30]:
function Cyclic(x,h)
    n=length(x)
    C_h=zeros(n,n)
    for i in 1:n
        for j in 1:n
            k=i+1-j
            if k<=0
                k=n+k
            end
            C_h[i,k]=h[j]
        end
    end
    C_star=transpose(C_h)
    return C_h,C_star 
end

A.Q4_3_4_a_ans_Operator,A.Q4_3_4_a_ans_AdjointOperator=Cyclic(A.Q4_3_4_data_x,A.Q4_3_4_data_h)

([0.9500237407025717 2.2523378283132285 … -0.3355742560381149 -1.252622449487755; -1.252622449487755 0.9500237407025717 … -1.0779405511934164 -0.3355742560381149; … ; -0.7442819493207524 -0.5762169532073635 … 0.9500237407025717 2.2523378283132285; 2.2523378283132285 -0.7442819493207524 … -1.252622449487755 0.9500237407025717], [0.9500237407025717 -1.252622449487755 … -0.7442819493207524 2.2523378283132285; 2.2523378283132285 0.9500237407025717 … -0.5762169532073635 -0.7442819493207524; … ; -0.3355742560381149 -1.0779405511934164 … 0.9500237407025717 -1.252622449487755; -1.252622449487755 -0.3355742560381149 … 2.2523378283132285 0.9500237407025717])

### 4.(b)

In [31]:
import DSP
function find4by(x,h)
    n=length(x)
    y=zeros(n)
    x_ex=repeat(x, outer=(3,))
    y=DSP.conv(x_ex,h)
    y_ans=y[n+1:2n]
    return y_ans
end
A.Q4_3_4_b_ans_y = find4by(A.Q4_3_4_data_x,A.Q4_3_4_data_h)

142-element Vector{Float64}:
  -0.6505373784033195
  17.62741253034949
  -0.16099701667292926
  15.91581493269945
  13.078120412775444
  11.240466792931896
 -20.39868062058624
   0.2816123254526924
  -3.172618311774635
   0.32601355043535385
   ⋮
  -4.4971743585573565
  -8.75309808871373
   9.650725697430005
 -15.844227065531346
   3.893551011069385
  -2.552353170774595
   6.962053168975658
  -9.103331523740948
 -13.93975454296985

### 4.(c)

In [32]:
function find4cz(y,h)
    n=length(y)
    z=zeros(n)
    h=reverse(h)
    h_ex=repeat(h, outer=(3,))
    z=DSP.conv(y,h_ex)
    z_ans=z[n:2n-1]
    return z_ans
end
A.Q4_3_4_c_ans_z=find4cz(A.Q4_3_4_b_ans_y,A.Q4_3_4_data_h)

142-element Vector{Float64}:
 -285.4178889536644
 -213.8557786586268
   20.825571705360137
  115.47778899008901
   61.440398215620576
 -364.2334472579603
   34.18014406875943
   50.06381340742321
  -65.00215441817535
  189.2023532884148
    ⋮
 -188.01254045179405
   67.43031876578027
   89.61976611092582
  -94.09717466451669
 -227.05493821917602
  300.42608973802515
    8.141598775171197
 -225.03428107948713
 -568.3838990156075

### 5.(a)

In [33]:
import FFTW
function MRI(x,omega)
    m,n=size(x)
    O1= FFTW.fft(x)
    O2= FFTW.fftshift(O1)
    O3= zeros(ComplexF64,m,n)
    for i in 1:m
        for j in 1:n
            if omega[i,j]==1
                O3[i,j]=O2[i,j]
            end
        end
    end
    O3=vec(O3)
    O3 = filter(x -> x != 0, vec(O3))
    return O1,O2,O3
end
A.Q4_3_5_a_ans_O1,
A.Q4_3_5_a_ans_O2,
A.Q4_3_5_a_ans_O3=
MRI(
    A.Q4_3_5_data_X,
    A.Q4_3_5_data_Omega
)

(ComplexF64[7991.164705882353 + 0.0im -3910.3010220423803 - 118.45124788344212im … -973.8855047234892 + 141.34581545030696im -3910.3010220423803 + 118.45124788344212im; -2637.6352164198715 - 414.0041161037336im 957.7537395017742 + 94.45223731386422im … 798.124782536756 + 307.38513700791464im 793.0829983834138 - 53.28594654502898im; … ; -1043.7904716544533 + 361.30523924569184im 737.0745236966186 - 278.1445179789142im … 160.3770987030368 - 54.3496634065702im 669.8075516813126 - 205.11240051499183im; -2637.6352164198715 + 414.0041161037336im 793.0829983834138 + 53.28594654502898im … 787.9458401059704 - 479.0693778240184im 957.7537395017742 - 94.45223731386422im], ComplexF64[33.17647058823525 + 0.0im -20.304382996097743 - 2.547913451843277im … 13.218450597843688 + 9.53767103916979im -20.304382996097743 + 2.547913451843277im; 1.1761498993100856 - 14.410057649895519im 9.175202157078726 + 17.212898158882485im … 56.94905777747435 - 47.62593481259198im -48.806498188098516 + 38.4589659098732im;

### 5.(b)

In [35]:
import FFTW
function IvMRI(y,omega)
    m,n=size(omega)

    vec_omega = vec(omega)
    O1 = complex(Array{Float64}(undef, length(vec_omega)))
    j = 1
    for i in 1:length(vec_omega)
        if vec_omega[i] != 0
            O1[i] = round(y[j]; digits = 8)
            j+=1
        end
    end
    O1=reshape(O1, m,n)
    O2=FFTW.ifftshift(O1)
    O3=FFTW.ifft(O2)
    return O1,O2,O3
end
A.Q4_3_5_b_ans_O1,
A.Q4_3_5_b_ans_O2,
A.Q4_3_5_b_ans_O3=
IvMRI(
    A.Q4_3_5_a_ans_O3,
    A.Q4_3_5_data_Omega
)

(ComplexF64[1.4829670885574e-311 + 0.0im 1.4829670865386e-311 + 0.0im … 5.0e-324 + 0.0im 5.0e-324 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im … -2.336084390963e-310 + 0.0im 5.0e-324 + 0.0im; … ; 1.4829679604894e-311 + 0.0im 1.69759663277e-313 + 0.0im … 5.0e-324 + 0.0im 5.0e-324 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im … 5.0e-324 + 0.0im 5.0e-324 + 0.0im], ComplexF64[5.0e-324 + 0.0im 5.0e-324 + 0.0im … 5.0e-324 + 0.0im 5.0e-324 + 0.0im; 5.0e-324 + 0.0im 5.0e-324 + 0.0im … 5.0e-324 + 0.0im 5.0e-324 + 0.0im; … ; 5.0e-324 + 0.0im 5.0e-324 + 0.0im … 5.0e-324 + 0.0im 5.0e-324 + 0.0im; 5.0e-324 + 0.0im 5.0e-324 + 0.0im … 5.0e-324 + 0.0im 5.0e-324 + 0.0im], ComplexF64[7.324137824005206e-12 + 1.2207027055843866e-11im 3.157753230847771e-12 - 1.0855790102968261e-11im … -9.808537577076357e-12 + 8.650011185524506e-12im -1.7195804826218854e-12 - 9.893030119948128e-12im; -1.7931569423756955e-11 - 1.7346393418882222e-11im 2.3009513091701223e-11 + 1.616373821384744e-11im … 8.209304385717608e-13 + 9.668180053680096e-12im 

## 5.1. The Netflix Problem

### 1.(a)

In [37]:
function update_V(y, Omega, U)
    #basically, the idea is to select relavent U rows for each column of V' base on sparsity matrix, then compute least square for each column of V'
    #Let the operator matrix be M (which is actually the observation matrix)
    m , n = size(Omega)
    r = size(U,2)
    k = 1   #for incrementing through y
    
    #initialize output
    V_new = zeros(r,n)
    
    #NOTE: m = height of m, n = height of V
    for j in 1:n    #along each column of omega same column = same v
        M_temp = zeros(1,r)
        little_y = vec([])
        for i in 1:m        #along each row of omega
            if Omega[i,j] == 1
                append!(little_y, y[k])
                M_temp = [M_temp;U[i,:]']
                k+=1
            end
        end
        M_temp = M_temp[2:end,:]
        V_col = (inv(M_temp'M_temp+I*1e-10))* M_temp' * little_y   #perturbate to avoid singularity
        
        V_new[:,j] = V_col
    end

    return V_new'
end

    A.Q5_1_a_ans_V = 
    update_V(
        A.Q5_1_data_y,
        A.Q5_1_data_Omega,
        A.Q5_1_data_Uini
    )

437×10 adjoint(::Matrix{Float64}) with eltype Float64:
  0.0502317    0.0281982   0.172274    0.271618   …  -0.127534    -0.335034
  0.229298     0.324551    0.0185116   0.210246      -0.483392     0.138116
  0.147375     0.235051   -0.294833    0.232546      -0.0748486    0.301312
 -0.087545    -0.0239002   0.169446    0.130266       0.00010314  -0.204198
  0.0392621    0.0740349  -0.412865   -0.13049        0.322348    -0.112906
 -0.392681     0.332684    0.0953439   0.226482   …  -0.471666    -0.0533835
  0.0774202   -0.0127447  -0.0886845  -0.0650795      0.295829     0.313306
  0.161588     0.112577    0.393306    0.166357      -0.454215     0.256181
  0.250072    -0.277306   -0.166693    0.179071      -0.0494303   -0.0484946
 -0.0133386   -0.029201    0.337616    0.0747999     -0.148557     0.241051
  ⋮                                               ⋱               
  0.0365293    0.402609   -0.255723    0.0592544     -0.238078     0.210013
 -0.113949    -0.12069     0.343671    0

### 1.(b)

In [38]:
function update_U(y, Omega, V)
    #Same idea as above
    #Let the operator matrix be M (which is actually the observation matrix)
    m , n = size(Omega)
    r = size(V,2)
    V = V'  #make v easier to work on
    #initialize output
    U_new = zeros(m,r)

    #reshape y because we are workign on a different index
    i = 1
    
    #NOTE: m = height of m, n = height of V
    for i in 1:m    
        M_temp = zeros(r,1)
        little_y = vec([])
        for j in 1:n        
            if Omega[1,j] == 1
                idx = sum(Omega[:,1:j-1]) + sum(Omega[1:i,j])   #find index of corrsponding y element
                append!(little_y, y[idx])
                M_temp = hcat(M_temp,V[:,j])
                
            end
        end
        M_temp = M_temp[:,2:end]
        U_row = little_y' * M_temp' * inv(M_temp * M_temp'+I*1e-10) #perturbate to avoid singularity
        U_new[i,:] = U_row
    end

    return U_new
end

    A.Q5_1_b_ans_U= 
    update_U(
        A.Q5_1_data_y,
        A.Q5_1_data_Omega,
        A.Q5_1_a_ans_V
    )



458×10 Matrix{Float64}:
  0.541509    -1.1926      1.02761    …  -0.119129  -4.68132     0.313116
  0.607825    -1.45745    -1.13906        1.2786    -3.05908     0.0248713
  0.00516628  -0.289921    0.0226983      0.902324  -1.56529     1.70394
 -0.317398    -0.742435    1.52624        1.05935   -0.894362    0.0681758
 -0.336443     1.98809    -0.0465536     -1.85611   -0.140559   -0.39134
 -0.697516     1.37119    -0.533764   …  -1.0838     0.0189006   0.194695
 -2.14557      0.128673    1.4762        -1.37251    2.69487     0.0994025
  0.785696    -2.52063     1.74457       -0.91928    3.18971    -0.20666
  0.728699    -1.62322     0.521954       1.27096    2.33866    -1.03882
 -1.42543     -0.696411    0.605105       0.173015   0.0100235   0.632471
  ⋮                                   ⋱                         
 -0.828922     0.0763181   1.20315       -0.259662   1.25623     0.0303646
 -1.00991      1.61799     0.891561   …   0.276728   1.27044     0.0723607
 -0.195666    -2.19759

### 1.(c)

In [39]:
function alt_min(iter, y, Omega,U_init)
    U = U_init
    V = zeros(size(Omega,2),size(U,2))
    
    for i in 1:iter
        V_new = update_V(y, Omega, U)
        V = V_new
        U_new = update_U(y, Omega, V)
        U = U_new

        #if i%10 == 0 #calculate loss every 10 iteration
            UV = U*V'
            PUV = Omega.*UV
            PUV_vec = vec(PUV)
            nonzeros = filter(x -> x != 0, PUV_vec)
            loss = norm(y - nonzeros)
            print("Iteration ",i,": ")
            print(loss)
            print("\n")
        #end
    end
    return U,V
end

A.Q5_1_c_ans_U,
A.Q5_1_c_ans_V = 
alt_min(
    10,
    A.Q5_1_data_y,
    A.Q5_1_data_Omega,
    A.Q5_1_data_Uini
)



Iteration 1: 965.7351876007737


Iteration 2: 939.6415950578867


Iteration 3: 934.8028479785607


Iteration 4: 933.0050342409867


Iteration 5: 931.9267653913695


Iteration 6: 931.2262476393527


Iteration 7: 930.8122687368265


Iteration 8: 930.591125309271


Iteration 9: 930.4866806948411


Iteration 10: 930.4508341798141


([0.46300126277479753 -0.6492349805763934 … -0.5889535922788757 0.4763726218587261; 0.13696452834330894 -0.5687412497234333 … -0.4436336447822415 0.26913084028554635; … ; 0.831732836767152 -0.4304975013679283 … 0.36110141693905484 0.09150088139716372; 0.4513224939274724 -0.27666590101666144 … -0.04033885253759613 -0.30233729486325844], [-0.009960625305494578 -0.7075484000010013 … 0.5910683334112277 -0.34625508964789; -0.9401449500726705 0.8875365668414129 … -0.05908307954228109 -1.0936873112468994; … ; 0.3862369794721708 -0.20169082151734147 … 0.5145097725481547 -0.09874437020658211; -0.27031772756064537 -0.06603999147630629 … 0.5126475751812177 -1.017035976666391])

## 5.2. Estimation Accuracy

### 1.(a)

In [40]:
function find_best_w(A)
    # Get SVD of A
    U, E, V = svd(inv(A))
    
    # choose last column (with smallest eigen value)
    best_w = V[:, end]

    # error = 
    error = norm(A\best_w)* norm(A\best_w)
    return best_w, error
end 


A.Q5_2_a_ans_w,
A.Q5_2_a_ans_err = 
find_best_w(
    A.Q5_2_data_A 
)



([0.22462675001189797, 0.21495238082128526, 0.2398948505308106, 0.17943971925068794, 0.21217436539822704, 0.2400556190048166, 0.24477615792376342, 0.23300155836784375, 0.2775232744113097, 0.19268792906483145, 0.20667162404858858, 0.2600211240347275, 0.2163596253846917, 0.1998757392736415, 0.24078424219820502, 0.2391999896705241, 0.19073744712580215, 0.2583587668700048, 0.2591966968066494], 0.00010643435146375388)

In [41]:
A.Q5_2_a_ans_err

0.00010643435146375388

### 1.(b)

In [42]:
function find_worst_w(A)
    # Get SVD of A
    U, E, V = svd(inv(A))
    
    # choose first column (with biggest eigen value)
    worst_w = V[:, 1]

    # error is easy to find
    error = norm(A\worst_w)*norm(A\worst_w)
    return worst_w, error
end 

A.Q5_2_b_ans_w,
A.Q5_2_b_ans_err = 
find_worst_w(
    A.Q5_2_data_A 
)



([-0.1298506588418091, 0.12624284972335906, 0.29822631693782875, -0.3675950891229983, -0.19485981127347754, -0.0996474186280977, -0.2631646886963739, 0.030831303598845266, 0.1131145881608186, -0.22329581218080272, 0.10580302166656079, 0.031457645994407715, 0.26438609790528456, -0.5171352135272335, -0.056556786667946786, 0.09159087246452602, 0.2469793108130403, 0.37397046775835424, -0.020528214931650905], 5.74042484932142e6)

In [53]:
A.Q5_2_b_ans_err


5.74042484932142e6

### 1.(c)

In [54]:
# average error
function average_error(A)
    sum = 0
    for i in 1:size(A,2)
        error = 0
        U, E, V = svd(inv(A))
        #for each noise
        w = V[:,i]
        #calculate error
        error = norm(A\w)*norm(A\w)
        sum += error
    end
    avg_error = sum / size(A,1)
    return avg_error 
end

A.Q5_2_c_ans_err =
average_error(
    A.Q5_2_data_A 
)


302213.3175277133

## 5.3. LS Recovery from Convolution

### 1.(a)

In [55]:
function find_Ab(y, h, Omega, alpha, n)
    #NOTE: dimension of x is n, which is the same as h
    #define our output
    A = zeros(n,n)
    b = zeros(n)
    #dummy varialbe x for getting cyclic convolution operator
    x = zeros(n)
    C1, C1_adj = Cyclic(x,h)
    S1, S1_adj = SubSampl_Op(n, Omega)
    #M is the overall operator on x
    M = S1 * C1

    A = transpose(M) * M - alpha * Matrix(I, n, n)
    b = - transpose(y) * M
    return A, transpose(b)
end

A.Q5_3_1_a_ans_A, 
A.Q5_3_1_a_ans_b = 
find_Ab(
    A.Q5_3_data_y,
    A.Q5_3_data_h,
    A.Q5_3_data_Omega, 
    A.Q5_3_data_alpha, 
    A.Q5_3_data_n
)


#Q5_3_1_a_ans_A
#Q5_3_1_a_ans_b

([58.58295690708637 16.749593606704543 … -8.543642336511715 2.944019978314911; 16.749593606704543 81.97414348242744 … -1.7888451225898336 3.382344204571132; … ; -8.543642336511715 -1.7888451225898336 … 70.1371201046607 11.802724893187971; 2.944019978314911 3.382344204571132 … 11.802724893187971 52.156062838153986], [-69.53828854742798, -173.70282395222205, 68.02940717907882, 87.82656217754106, 105.01011580268937, -82.29628114500485, 27.990285549601616, 35.80108482638736, 47.63359426380435, -90.44024974873224  …  51.964166381064956, 22.13599268170875, -36.48992152928214, -11.505692973005765, -194.32868159388516, -116.12801383503677, 26.703281592845098, 117.11984970259122, 122.38418026362703, -98.38141712432262])

### 1(b)

In [46]:
A.Q5_3_1_b_ans_x = A.Q5_3_1_a_ans_A\A.Q5_3_1_a_ans_b

135-element Vector{Float64}:
  0.34094877180210825
 -0.8600716274528826
  0.12798927500187035
  0.21133650441099414
  0.8267088419110429
 -0.539878594671811
 -0.09827220205722605
 -0.11154584086027951
 -0.18505371860852823
 -0.2077749308133293
  ⋮
  0.6250567685259288
  0.15620810996582782
 -0.43565782549336235
 -1.2888760234481316
 -0.4316232712678664
  0.2884048284631091
  1.2279036271681685
  0.6660082123597082
 -0.43378982909887603

### 2.(a)

In [56]:
function mat_free_uAv(u,v,y,h,Omega,alpha,n)
    #uAv is basically:
    #get h*v
    Hv = zeros(n) 
    Hv = find4by(h,v)       #call function in 4.4
    #get Phv
    PHv = Subsample(Hv, Omega)      #call function in 4.1
    #get PtPhv
    PtPHv = Subsample_adj(PHv,Omega,n)  #call function in 4.1
    #get htPtPhv
    HtPtPHv = find4cz(PtPHv,h)      #call function in 4.4 
    #get uHtPtPhv
    uHtPtPhv = u' * HtPtPHv
    #get alpha * u * v
    ualphav = alpha * u' *v
    uAv = uHtPtPhv - ualphav  
    return uAv
end

function mat_free_bu(u,y,h,Omega,n)
    #bu = -y' * P * H * u
    #we apply each operators in function form one by one
    Hu = find4by(h,u)
    PHu = Subsample(Hu, Omega)
    #then multiply by y
    yPHu = y'*PHu
    bu = -yPHu
    return bu
end

# Assign to answer
A.Q5_3_2_a_ans_uAv = 
mat_free_uAv(
     A.Q5_3_data_u,
     A.Q5_3_data_v,
     A.Q5_3_data_y,
     A.Q5_3_data_h,
     A.Q5_3_data_Omega,
     A.Q5_3_data_alpha,
     A.Q5_3_data_n
 )

 A.Q5_3_2_a_ans_bu = 
 mat_free_bu(
     A.Q5_3_data_u,
     A.Q5_3_data_y,
     A.Q5_3_data_h,
     A.Q5_3_data_Omega,
     A.Q5_3_data_n
 )

#Q5_3_2_a_ans_uAv
#Q5_3_2_a_ans_bu


-650.0147060148207

### 2.(b)

In [48]:
using LinearOperators
using IterativeSolvers
function iterate_solve(A,b)
    
    Op = LinearOperator(A)
    x = cg(Op, b)
    return x
end

A.Q5_3_2_b_ans_x = 
iterate_solve(
    A.Q5_3_1_a_ans_A,
    A.Q5_3_1_a_ans_b
)

135-element Vector{Float64}:
  0.3409487692315657
 -0.8600716162927828
  0.12798926967868604
  0.2113365094192934
  0.8267088344229716
 -0.5398785913997967
 -0.09827221197580181
 -0.11154584656995407
 -0.18505373317293858
 -0.20777493191484575
  ⋮
  0.6250567739989742
  0.15620811310518012
 -0.43565782910179107
 -1.2888760206058443
 -0.4316232618307871
  0.28840482745417334
  1.2279036230756923
  0.6660082036887459
 -0.43378983608705834

## 5.4. LS Recovery for MRI

### 1.(a)

In [49]:
function find_obs_y(X, Omega)
    O1 = FFTW.fft(X)
    O2 = FFTW.fftshift(O1)
    O3 = Omega .* O2        #Omega.*O2 is basically subsample and subsample_adj applied together
    nonzeros = filter(x -> x != 0, vec(O3))
    return nonzeros
end 

A.Q5_4_1_a_ans_y =  
find_obs_y(
    A.Q5_4_data_X,
    A.Q5_4_data_Omega,
)

133873-element Vector{ComplexF64}:
  17.690196078431065 + 0.0im
 -2.7916380224123856 + 4.7243407481078314im
  -5.120918035843408 - 0.4366884910380122im
  7.2336004515712835 + 4.286073964967405im
 -1.1578716150208663 - 7.3334982787780145im
   2.780380984161915 - 0.25837501968199783im
  0.2132505171248209 - 7.461145119286617im
  -4.762147570510076 + 8.339476611824278im
 -2.9175859182368513 + 1.8641863470170907im
  0.5139426737833084 - 2.675620088016424im
                     ⋮
  -19.46176402884703 - 4.567088921055046im
   30.36337821109737 + 7.384069438336155im
  -17.21631035964856 + 5.169204053060639im
  11.393302601280084 - 14.356025302960006im
  20.478046478326178 - 3.158968055575315im
 -2.7767831088858657 + 5.9427612695701555im
  -7.040162422261346 - 12.09269452294808im
  -3.372030633065151 + 5.179175628108908im
 -15.529497348339646 + 9.587104911465644im

### 1.(b)

In [50]:
function find_UAV(U, V, y, Omega, alpha)
    O1 = FFTW.fft(V')
    O2 = FFTW.fftshift(O1)
    O2_reshape = reshape(O2, size(Omega,1), size(Omega,2))
    O4 = Omega .* O2_reshape        #Omega .* O2 is basically subsample_adj of subsample of O2
    O4_vec = vec(O4)
    O5=FFTW.ifftshift(O4_vec)
    O6=FFTW.ifft(O5)
    alpha_over_two = alpha*U'*V     #jk, no need over two
    output = U'*O6 + alpha_over_two
    return real(output)

end

function find_bz(z,y,Omega)
    O1 = FFTW.fft(z)
    O2 = FFTW.fftshift(O1)
    O2_reshape = reshape(O2, size(Omega,1), size(Omega,2))
    O3 = Omega .* O2_reshape
    Mz = filter(x -> x != 0, vec(O3)) #filter out zero elements in O3
    yMz = y'*Mz
    return real(-yMz)
end

#Assign to answers
A.Q5_4_1_b_ans_uAv = 
find_UAV(
    A.Q5_4_data_u,
    A.Q5_4_data_v,
    A.Q5_4_1_a_ans_y,
    A.Q5_4_data_Omega,
    A.Q5_4_data_alpha,
)

A.Q5_4_1_b_ans_bz = 
find_bz(
    A.Q5_4_data_z,
    A.Q5_4_1_a_ans_y,
    A.Q5_4_data_Omega,
)


-1.0667139488817787e8

### 1.(c)

In [51]:
y = A.Q5_4_1_a_ans_y
Omega = A.Q5_4_data_Omega
alpha = A.Q5_4_data_alpha

function Map_A(X)
    #return find_UAV(X, X, y, Omega, alpha)
    X_reshaped = reshape(X, size(Omega))        #make sure shape of X is fitting with Omega
    O1 = FFTW.fft(X_reshaped)
    O2 = FFTW.fftshift(O1)
    O3 = Omega .* O2
    MtMx = FFTW.ifft(FFTW.ifftshift(O3))
    output2 = MtMx - alpha*X_reshaped
    return real(output2)
end


function find_Xhat(X)
    m, n = size(X)
    #make linear map
    op = LinearMap(Map_A, m*n)  
    #now get vector b
    b = real(Array{Float64}(undef, m*n))
    Y = Omega .* FFTW.fftshift(FFTW.fft(X))
    b = real(FFTW.ifft(FFTW.fftshift(Y)))
    #use cg to solve for xhat
    xhat = Matrix{Float64}(undef,m,n)
    xhat = cg(op, b, maxiter=1000)
    xhat = reshape(xhat, m, n)
    #reshape(xhat, 512,512)
    return xhat
end 

A.Q5_4_1_c_ans_X_hat = 
find_Xhat(
    A.Q5_4_data_X
)


512×512 Matrix{Float64}:
 0.228479  0.239335  0.236678  0.224692  …  0.21737   0.207665  0.211266
 0.232344  0.247149  0.243229  0.234481     0.221064  0.212375  0.216634
 0.237444  0.250307  0.251068  0.241891     0.224399  0.215236  0.219534
 0.241454  0.255331  0.257867  0.250174     0.227362  0.218546  0.223218
 0.245131  0.260027  0.264381  0.258222     0.229939  0.221522  0.226584
 0.248462  0.264381  0.270594  0.26602   …  0.232118  0.224152  0.22962
 0.251433  0.268379  0.276491  0.273551     0.233888  0.226422  0.232313
 0.254032  0.272008  0.282057  0.2808       0.235236  0.22832   0.23465
 0.256247  0.275256  0.287277  0.287749     0.236152  0.229837  0.23662
 0.257296  0.280287  0.291366  0.295473     0.236624  0.231729  0.2393
 ⋮                                       ⋱            ⋮         
 0.181497  0.181016  0.161409  0.138951     0.172182  0.169512  0.170583
 0.182606  0.186466  0.167134  0.143332     0.174396  0.172801  0.172241
 0.194294  0.201859  0.186824  0.163047