# Coursework 2

### PLAGIARISM/COLLUSION DECLARATION

 

Coursework submitted for assessment must be the original work of you and your group. Assignments are subjected to regular checks for plagiarism and/or collusion. Plagiarism is the presentation of another person’s thoughts or words (those outside your group) as if they were your own. Collusion involves obtaining help from someone outside your group to complete your work. In preparing your coursework, you should not seek help, or copy from any other person or source, including the

Internet, without proper and explicit acknowledgement.

 

There is a procedure in place for you to declare individual contributions within your group for courswork. You must declare the contributions fairly and accurately.

 

You must not disclose your solutions or insights related to coursework with anyone else, including future students or the Internet.

 

By acknowledging the the statements above, you are declaring that both this and all subsequent pieces of coursework are, and will remain, the original work of you and your group.

 

* Submissions will not be accepted without the aforementioned declaration.

 

* Members of a group are deemed to have collective responsibility for the integrity for work submitted and are liable for any penalty imposed, proportionate to their contributions.

In [1]:
using JLD2,FileIO
using LinearAlgebra
using Wavelets
using FFTW

In [2]:
# Run this code before you start doing the coursework

Base.@kwdef mutable struct CourseWork_1
    
    CID::Int
    Plagiarism_declare::Union{Missing,Bool}
    Demo_willing::Union{Missing,Bool}
    
    # 6.1 Proximal Operator
    
    Q6_1_a_data_A::Matrix
    Q6_1_a_data_b::Vector
    Q6_1_a_data_z::Vector
    Q6_1_a_data_gamma::Float64
    
    Q6_1_a_ans_x::Union{Missing,Vector}
    
    Q6_1_b_data_z::Vector
    Q6_1_b_data_a::Float64
    Q6_1_b_data_b::Float64
    Q6_1_b_data_gamma::Float64
    
    Q6_1_b_ans_x::Union{Missing,Vector}
    
    Q6_1_c_data_z::Vector
    Q6_1_c_data_k::Int
    Q6_1_c_data_gamma::Float64
    
    Q6_1_c_ans_x::Union{Missing,Vector}
    
    Q6_1_d_data_z::Vector
    Q6_1_d_data_gamma::Float64
    
    Q6_1_d_ans_x::Union{Missing,Vector}
    
    Q6_1_e_data_Z::Matrix
    Q6_1_e_data_r::Int
    Q6_1_e_data_gamma::Float64
    
    Q6_1_e_ans_X::Union{Missing,Matrix}
    
    Q6_1_f_data_Z::Matrix
    Q6_1_f_data_gamma::Float64
    
    Q6_1_f_ans_X::Union{Missing,Matrix}
    
    Q6_1_g_data_Z::Matrix
    Q6_1_g_data_gamma::Float64
    
    Q6_1_g_ans_X::Union{Missing,Matrix}
    
    Q6_1_h_data_z::Vector
    Q6_1_h_data_gamma::Float64
    
    Q6_1_h_ans_x::Union{Missing,Vector}
    
    # 6.2 Proximal operators related to ℓ1-norm
    
    Q6_2_a_data_z::Vector
    Q6_2_a_data_gamma::Float64
    Q6_2_a_data_lambda::Float64
    
    Q6_2_a_ans_x::Union{Missing,Vector}
    
    Q6_2_b_data_z::Vector
    Q6_2_b_data_a::Vector
    Q6_2_b_data_gamma::Float64
    Q6_2_b_data_lambda::Float64
    
    Q6_2_b_ans_x::Union{Missing,Vector}
    
    Q6_2_c_data_z::Vector
    Q6_2_c_data_U::Matrix
    Q6_2_c_data_gamma::Float64
    Q6_2_c_data_lambda::Float64
    
    Q6_2_c_ans_x::Union{Missing,Vector}
    
    Q6_2_d_data_z::Vector
    Q6_2_d_data_U::Matrix
    Q6_2_d_data_gamma::Float64
    Q6_2_d_data_lambda::Float64
    
    Q6_2_d_ans_x::Union{Missing,Vector}
    
    # 7.1 Greedy Algorithms
    
    Q7_1_1_data_y::Vector
    Q7_1_1_data_A::Matrix
    Q7_1_1_data_S::Int
    
    Q7_1_1_ans_x::Union{Missing,Vector}
    
    Q7_1_2_data_y::Vector
    Q7_1_2_data_A::Matrix
    Q7_1_2_data_S::Int
    
    Q7_1_2_ans_x::Union{Missing,Vector}
    
    Q7_1_3_data_y::Vector
    Q7_1_3_data_A::Matrix
    Q7_1_3_data_S::Int
    
    Q7_1_3_ans_x::Union{Missing,Vector}
    
    # 7.2 Proximal Gradient Method
    
    Q7_2_1_data_z::Vector
    Q7_2_1_data_xini::Vector
    Q7_2_1_data_A::Matrix
    Q7_2_1_data_lambda::Float64
    Q7_2_1_data_gamma::Float64
    
    Q7_2_1_ans_xhat::Union{Missing,Vector}
    Q7_2_1_ans_subgradient::Union{Missing,Vector}
    
    Q7_2_2_data_z::Vector
    Q7_2_2_data_A::Matrix
    Q7_2_2_data_lambda::Float64
    
    Q7_2_2_ans_objfun::Union{Missing,Vector}
    
    # 7.3 MRI CS Recovery: Wavelet
    
    Q7_3_1_data_X0::Matrix
    Q7_3_1_data_Omega::Matrix
    Q7_3_1_data_y::Vector
    
    Q7_3_1_ans_gradient::Union{Missing,Matrix}
    
    Q7_3_2_data_lambda::Float64
    
    Q7_3_2_ans_X1::Union{Missing,Matrix}
    
    Q7_3_3_ans_X::Union{Missing,Matrix}
    
    # 7.4 MRI CS Recovery: DCT
    
    Q7_4_1_data_X0::Matrix
    Q7_4_1_data_Omega::Matrix
    Q7_4_1_data_y::Vector
    Q7_4_1_data_lambda::Float64
    
    Q7_4_1_ans_X1::Union{Missing,Matrix}
    
    Q7_4_2_ans_X::Union{Missing,Matrix}
    
    # 7.5 MRI CS Recovery: Wavelet and DCT
    
    Q7_5_1_data_Z1::Matrix
    Q7_5_1_data_Z2::Matrix
    Q7_5_1_data_Omega::Matrix
    Q7_5_1_data_y::Vector
    Q7_5_1_data_lambda::Float64
    Q7_5_1_data_alpha::Float64
    
    Q7_5_1_ans_X1::Union{Missing,Matrix}
    
    Q7_5_2_ans_Z1::Union{Missing,Matrix}
    Q7_5_2_ans_Z2::Union{Missing,Matrix}
    
    Q7_5_3_ans_X::Union{Missing,Matrix}
    
end

CourseWork_1

In [42]:
# Download and upload data from JLD file, refer to https://juliaio.github.io/JLD2.jl/dev/
# Example
A = JLD2.load("Laurie Johnston1705019StudentFile.jld2");
A = A[ "CourseWork_1" ];
A.Demo_willing = true;


In [4]:
jldopen("Laurie Johnston1705019StudentFile.jld2", "w") do file
    write(file, "CourseWork_1", A)
  end

## 6.1. Proximal Operator


### 1. (a)

In [5]:
# save your answers in Q6_1_a_ans_x
function Q6_11a() 

### 1. (b)

In [6]:
# save your answers in Q6_1_b_ans_x


### 1. (c)

In [7]:
# save your answers in Q6_1_c_ans_x

### 1. (d)

### 1. (e)

### 1. (f)

### 1. (g)

### 1. (h)

### 2. (a)

### 2. (b)

### 2. (c)

### 2. (d)

In [63]:
z = A.Q6_2_d_data_z
U = A.Q6_2_d_data_U
gamma = A.Q6_2_d_data_gamma
lambda = A.Q6_2_d_data_lambda

# using the solution from this derivation online: https://math.stackexchange.com/questions/1961888/the-proximal-operator-of-the-l-1-norm-function 
x = U' * ((sign.(U*z) .* max.((abs.(U*z) .- (lambda * gamma)), 0.0)))

# print error and have a look
error = (lambda * norm((U*x), 1)) + ((1/(2*gamma)) * (norm((x-z), 2)^2)) 
println(error)

A.Q6_2_d_ans_x = x;


20.59085435909057


## 7.1. Greedy Algorithms

### 1

### 2

### 3

## 7.2. Proximal Gradient Method

### 1

### 2

### 3

## 7.3. MRI CS Recovery: Wavelet

### 1

In [8]:
# function MRI(x,omega)
#     m,n=size(x)
#     O1= fft(x)
#     O2= fftshift(O1)
#     O3= zeros(ComplexF64,m,n)
#     for i in 1:m
#         for j in 1:n
#             if omega[i,j]==1
#                 O3[i,j]=O2[i,j]
#             end
#         end
#     end
#     O3=vec(O3)
#     O3 = filter(x -> x != 0, vec(O3))
#     return O1,O2,O3
# end

# function IvMRI(y,omega)
#     m,n=size(omega)

#     vec_omega = vec(omega)
#     O1 = complex(Array{Float64}(undef, length(vec_omega)))
#     j = 1
#     for i in 1:length(vec_omega)
#         if vec_omega[i] != 0
#             O1[i] = round(y[j]; digits = 8)
#             j+=1
#         end
#     end
#     O1=reshape(O1, m,n)
#     O2=ifftshift(O1)
#     O3=ifft(O2)
#     return O1,O2,O3
# end


# Ay = 
# find_Ay(
#     A.Q7_3_1_data_Omega,
#     A.Q7_3_1_data_y
# )

# AAX = 
# find_AAX(
#     A.Q7_3_1_data_Omega,
#     A.Q7_3_1_data_X0
# )

IvMRI (generic function with 1 method)

In [69]:
function find_Ay(Omega, y)
    vec_omega = vec(Omega)
    O1 = complex(Array{Float64}(undef, length(vec_omega)))
    j = 1
    for i in 1:length(vec_omega)
        if vec_omega[i] != 0
            O1[i] = y[j]
            j+=1
        end
    end
    O1 = reshape(O1,512,512)
    O2=ifftshift(O1)
    O3=ifft(O2)

    return O3
end

function find_AAX(Omega,X)
    O1 = fft(X)
    O2 = fftshift(O1)
    O4O3 = Omega .* O2
    O5 = ifftshift(O4O3)
    O6 = ifft(O5)

    return O6
end


function find_grad(X, Omega, y)
    return - find_Ay(Omega, y) + find_AAX(Omega, X)

end

A.Q7_3_1_ans_gradient = 
find_grad(
    A.Q7_3_1_data_X0,
    A.Q7_3_1_data_Omega,
    A.Q7_3_1_data_y
)




512×512 Matrix{ComplexF64}:
  0.0383672+0.760606im    0.686698+0.0784548im  …   -0.813728-0.104892im
     1.5176+0.214358im    0.963876-0.0289204im        2.14156-0.285411im
   0.628935+0.151152im    0.709858+0.0448283im       0.869796-0.205352im
   0.829263+0.217057im     1.27397-0.449533im       -0.426368+0.23571im
   0.540524+0.248817im  -0.0394279+0.123263im       -0.113208+0.10886im
  0.0796532+0.392576im  -0.0891086+0.323551im   …    -0.42816-0.0212641im
    1.43034+0.330078im   -0.738538+0.0774436im      0.0182275+0.0671887im
  -0.111325+0.203347im   -0.298139+0.364208im        0.595705-0.0029911im
  -0.677165-0.215526im   -0.198593-0.127702im       -0.750175-0.0142763im
   0.529782-0.343197im     1.14369-0.369069im        -1.24618+0.136909im
           ⋮                                    ⋱  
   0.131527+0.663346im    0.606727-0.315423im         1.41992+0.388969im
     0.3701+0.495623im    -0.50695+0.117072im       -0.562976+0.0780068im
   0.299432+0.167881im    -1.22638-0.4034

### 2

In [17]:
#NOTE: the wavelet operator is unitary


512×512 Matrix{ComplexF64}:
 -0.00628388+0.778281im   …    -0.856215-0.0954219im
     1.47057+0.230216im          2.09628-0.277496im
    0.582881+0.165845im         0.827765-0.197875im
    0.785899+0.23034im         -0.467232+0.241427im
     0.49917+0.265415im        -0.146792+0.115741im
   0.0408234+0.408704im   …     -0.45498-0.0152262im
     1.39401+0.346765im      -0.00765481+0.0762864im
   -0.138033+0.21662im          0.579304+0.00302556im
    -0.69235-0.204453im        -0.756772-0.010924im
    0.516881-0.333238im         -1.25665+0.139832im
            ⋮             ⋱  
    0.134085+0.65223im           1.43547+0.391036im
    0.358867+0.484271im        -0.562384+0.0764377im
     0.28636+0.161549im   …    -0.243328+0.450327im
   -0.652516+0.665229im        -0.148542+0.395692im
   -0.156964+0.193722im        -0.324802-0.287826im
     -0.2203+0.409472im       -0.0933765+0.154824im
   -0.265767-0.0947471im       -0.100472-0.161379im
    0.165005-0.785617im   …   -0.0661888+0.186088im


In [49]:
idwt(dwt(A.Q7_3_1_data_X0, wavelet(WT.db4)),  wavelet(WT.db4))
A.Q7_3_1_data_X0


512×512 Matrix{Float64}:
  0.050993    0.884602    1.63468     …  -0.387344    1.70118    -0.797336
  2.35603     0.487945    0.914408        0.785467   -0.499912    2.69074
  0.641159    1.65587    -1.75428         0.46118    -0.766145    1.64587
  0.985662    1.45075    -0.902871       -0.594627    0.10435     0.495392
  0.227738   -0.0854534  -0.927935       -1.85779     0.75151    -0.793389
 -0.47866    -0.131528    0.0675058   …   1.79688     0.67092    -0.509162
  1.90157    -1.23103     1.52313         0.354436   -0.0817343  -0.22772
  0.0643615  -0.699978    0.0288933       0.0945019   0.431125    0.523342
 -0.792352   -1.11682     1.23983         0.192795    0.144052   -1.2456
  0.613097    1.57057     0.757151        0.435444   -1.62746    -2.39509
  ⋮                                   ⋱               ⋮          
  1.4367      0.780559    0.755408        1.48021     0.64596     1.64069
  1.25417    -0.268656    1.42604         0.332753    0.0933888  -0.996121
  0.396225   -1.

### 3

In [ ]:
S

## 7.4. MRI CS Recovery: DCT

### 1

In [52]:
idct(dct(A.Q7_4_1_data_X0)) - A.Q7_4_1_data_X0

512×512 Matrix{Float64}:
 -6.245e-17     4.44089e-16   4.44089e-16  …  -2.22045e-16  -2.22045e-16
  4.44089e-16   1.66533e-16  -1.11022e-16     -1.66533e-16   0.0
 -7.77156e-16   0.0           2.22045e-16     -8.88178e-16   0.0
  8.88178e-16   6.66134e-16   3.33067e-16      4.71845e-16  -6.10623e-16
  6.38378e-16  -9.71445e-17  -5.55112e-16      2.22045e-16  -3.33067e-16
  1.66533e-16  -1.38778e-16   3.05311e-16  …  -1.11022e-16  -6.66134e-16
  0.0           0.0           2.22045e-16      1.249e-16    -1.38778e-16
 -4.16334e-17   3.33067e-16   2.32453e-16     -3.33067e-16  -7.77156e-16
  1.11022e-16  -6.66134e-16   4.44089e-16     -2.77556e-17  -4.44089e-16
 -2.22045e-16  -4.44089e-16   5.55112e-16      4.44089e-16   0.0
  ⋮                                        ⋱   ⋮            
 -2.22045e-16  -1.11022e-16   5.55112e-16     -2.22045e-16  -4.44089e-16
 -2.22045e-16  -6.10623e-16  -2.22045e-16      3.747e-16     0.0
  6.66134e-16   0.0          -1.15793e-16  …   2.77556e-16   0.0
  4.4

### 2

## 7.5. MRI CS Recovery: Wavelet and DCT

### 1

### 2