# Coursework 1 

### PLAGIARISM/COLLUSION DECLARATION

 

Coursework submitted for assessment must be the original work of you and your group. Assignments are subjected to regular checks for plagiarism and/or collusion. Plagiarism is the presentation of another person’s thoughts or words (those outside your group) as if they were your own. Collusion involves obtaining help from someone outside your group to complete your work. In preparing your coursework, you should not seek help, or copy from any other person or source, including the

Internet, without proper and explicit acknowledgement.

 

There is a procedure in place for you to declare individual contributions within your group for courswork. You must declare the contributions fairly and accurately.

 

You must not disclose your solutions or insights related to coursework with anyone else, including future students or the Internet.

 

By acknowledging the the statements above, you are declaring that both this and all subsequent pieces of coursework are, and will remain, the original work of you and your group.

 

* Submissions will not be accepted without the aforementioned declaration.

 

* Members of a group are deemed to have collective responsibility for the integrity for work submitted and are liable for any penalty imposed, proportionate to their contributions.

In [44]:
import Pkg
Pkg.add("DSP")
Pkg.add("FFTW")
Pkg.add("LinearOperators")
Pkg.add("IterativeSolvers")

using JLD2,FileIO
using LinearAlgebra

   Resolving package versions...
  No Changes 

to `C:\Users\honan\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\honan\.julia\environments\v1.9\Manifest.toml`


   Resolving package versions...
  No Changes to `C:\Users\honan\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\honan\.julia\environments\v1.9\Manifest.toml`


   Resolving package versions...


  No Changes to `C:\Users\honan\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\honan\.julia\environments\v1.9\Manifest.toml`


   Resolving package versions...


  No Changes to `C:\Users\honan\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\honan\.julia\environments\v1.9\Manifest.toml`


In [45]:
# Run this code before you start doing the coursework

Base.@kwdef mutable struct CourseWork_1
    CID::Int
    Plagiarism_declare::Union{Missing,Bool}
    Demo_willing::Union{Missing,Bool}
    
    # 4.1. Trace and Inner Product of Matrices
    
    Q4_1_1_data_m::Int
    Q4_1_1_data_n::Int
    
    Q4_1_1_a_ans_rows::Union{Missing,Int}
    Q4_1_1_a_ans_columns::Union{Missing,Int}
    Q4_1_1_b_ans_rows::Union{Missing,Int}
    Q4_1_1_b_ans_columns::Union{Missing,Int}
    Q4_1_1_c_ans::Union{Missing,Bool}
    
    Q4_1_2_ans::Union{Missing,Bool}
    
    Q4_1_3_data_k::Int
    Q4_1_3_data_l::Int
    Q4_1_3_data_m::Int
    Q4_1_3_data_n::Int

    Q4_1_3_a_ans_Urows::Union{Missing,Int}
    Q4_1_3_a_ans_Ucolumns::Union{Missing,Int}
    Q4_1_3_a_ans_Vrows::Union{Missing,Int}
    Q4_1_3_a_ans_Vcolumns::Union{Missing,Int}
    Q4_1_3_b_ans::Union{Missing,Bool}
    
    # 4.2. The Matrix of the Linear Map
    
    Q4_2_1_ans::Union{Missing,Bool}
    
    # 4.3. Adjoint Operator
    
    Q4_3_1_data_n::Int
    Q4_3_1_data_Omega::Vector{Int}
    Q4_3_1_data_x::Vector
   
    Q4_3_1_a_ans_Operator::Union{Missing,Matrix}
    Q4_3_1_a_ans_AdjointOperator::Union{Missing,Matrix}
    Q4_3_1_b_ans_y::Union{Missing,Vector}
    Q4_3_1_c_ans_z::Union{Missing,Vector}
    
    
    Q4_3_2_data_p::Int
    Q4_3_2_data_q::Int
    Q4_3_2_data_x::Vector
    
    Q4_3_2_a_ans_Operator::Union{Missing,Matrix}
    Q4_3_2_a_ans_AdjointOperator::Union{Missing,Matrix}
    Q4_3_2_b_ans_H::Union{Missing,Matrix}
    Q4_3_2_c_ans_z::Union{Missing,Vector}
    Q4_3_2_d_ans::Union{Missing,Vector}
    
    Q4_3_3_data_h::Vector
    Q4_3_3_data_x::Vector
    
    Q4_3_3_a_ans_Operator::Union{Missing,Matrix}
    Q4_3_3_a_ans_AdjointOperator::Union{Missing,Matrix}
    Q4_3_3_b_ans_y::Union{Missing,Vector}
    Q4_3_3_c_ans_z::Union{Missing,Vector}
    
    Q4_3_4_data_h::Vector
    Q4_3_4_data_x::Vector
    
    Q4_3_4_a_ans_Operator::Union{Missing,Matrix}
    Q4_3_4_a_ans_AdjointOperator::Union{Missing,Matrix}
    Q4_3_4_b_ans_y::Union{Missing,Vector}
    Q4_3_4_c_ans_z::Union{Missing,Vector}
    
    Q4_3_5_data_X::Matrix{Float64}
    Q4_3_5_data_Omega::Matrix
    
    Q4_3_5_a_ans_O1::Union{Missing,Matrix}
    Q4_3_5_a_ans_O2::Union{Missing,Matrix}
    Q4_3_5_a_ans_O3::Union{Missing,Vector}
    Q4_3_5_b_ans_O1::Union{Missing,Matrix}
    Q4_3_5_b_ans_O2::Union{Missing,Matrix}
    Q4_3_5_b_ans_O3::Union{Missing,Matrix}
    
    # 5.1. The Netflix Problem
    
    Q5_1_data_y::Vector
    Q5_1_data_Omega::Matrix
    Q5_1_data_Uini::Matrix{Float64}
    
    Q5_1_a_ans_V::Union{Missing,Matrix}
    Q5_1_b_ans_U::Union{Missing,Matrix}
    Q5_1_c_ans_U::Union{Missing,Matrix}
    Q5_1_c_ans_V::Union{Missing,Matrix}
    
    
    # 5.2. Estimation Accuracy
    
    Q5_2_data_A::Matrix{Float64}
    
    Q5_2_a_ans_w::Union{Missing,Vector}
    Q5_2_a_ans_err::Union{Missing,Float64}
    Q5_2_b_ans_w::Union{Missing,Vector}
    Q5_2_b_ans_err::Union{Missing,Float64}
    Q5_2_c_ans_err::Union{Missing,Float64}
    
    # 5.3. LS Recovery from Convolution
    
    Q5_3_data_y::Vector
    Q5_3_data_h::Vector
    Q5_3_data_Omega::Vector
    Q5_3_data_n::Int
    Q5_3_data_alpha::Float64
    Q5_3_data_u::Vector
    Q5_3_data_v::Vector
    
    Q5_3_1_a_ans_A::Union{Missing,Matrix}
    Q5_3_1_a_ans_b::Union{Missing,Vector}
    Q5_3_1_b_ans_x::Union{Missing,Vector}
    Q5_3_2_a_ans_uAv::Union{Missing,Float64}
    Q5_3_2_a_ans_bu::Union{Missing,Float64}
    Q5_3_2_b_ans_x::Union{Missing,Vector}
    
    # 5.4. LS Recovery for MRI
    
    Q5_4_data_X::Matrix
    Q5_4_data_Omega::Matrix
    Q5_4_data_alpha::Float64
    Q5_4_data_u::Vector{Float64}
    Q5_4_data_v::Vector{Float64}
    Q5_4_data_z::Vector{Float64}
    
    Q5_4_1_a_ans_y::Union{Missing,Vector}
    Q5_4_1_b_ans_uAv::Union{Missing,Float64}
    Q5_4_1_b_ans_bz::Union{Missing,Float64}
    Q5_4_1_c_ans_X_hat::Union{Missing,Matrix}
end

CourseWork_1

In [46]:
# Download and upload data from JLD file, refer to https://juliaio.github.io/JLD2.jl/dev/
# Example
# A = JLD2.load("xxx.jld2");
# A = A[ "CourseWork_1" ];
# A.Demo_willing = true;
# jldopen("xxx.jld2", "w") do file
#    write(file, "CourseWork_1", A)

A = JLD2.load("Chin Young Anson, Hon1260366StudentFile.jld2")
A = A["CourseWork_1"];
A.Demo_willing = true;

jldopen("Chin Young Anson, Hon1260366StudentFile.jld2", "w") do file
    write(file, "CourseWork_1", A)
    print("done")
end

# end

done

In [47]:
A = JLD2.load("Chin Young Anson, Hon1260366StudentFile.jld2")
show(A["CourseWork_1"].Q4_1_1_data_n)

96

## 4.1. Trace and Inner Product of Matrices


### 1. (a)

In [5]:
# save your answers in Q4_1_1_a_ans_rows, Q4_1_1_a_ans_columns
A["CourseWork_1"].Q4_1_1_a_ans_rows = A["CourseWork_1"].Q4_1_1_data_m
A["CourseWork_1"].Q4_1_1_a_ans_columns = A["CourseWork_1"].Q4_1_1_data_n

96

### 1. (b)

In [6]:
# save your answers in Q4_1_1_b_ans_rows, Q4_1_1_b_ans_columns
A["CourseWork_1"].Q4_1_1_b_ans_rows = A["CourseWork_1"].Q4_1_1_data_n
A["CourseWork_1"].Q4_1_1_b_ans_columns = A["CourseWork_1"].Q4_1_1_data_m

22

### 1. (c)

In [7]:
# save your answers in Q4_1_1_c_ans
A["CourseWork_1"].Q4_1_1_c_ans = true

true

### 2

In [8]:
A["CourseWork_1"].Q4_1_2_ans = true

true

### 3. (a)

In [9]:
A["CourseWork_1"].Q4_1_3_a_ans_Urows = A["CourseWork_1"].Q4_1_3_data_m
A["CourseWork_1"].Q4_1_3_a_ans_Ucolumns = A["CourseWork_1"].Q4_1_3_data_k
A["CourseWork_1"].Q4_1_3_a_ans_Vrows = A["CourseWork_1"].Q4_1_3_data_l
A["CourseWork_1"].Q4_1_3_a_ans_Vcolumns = A["CourseWork_1"].Q4_1_3_data_n

34

In [10]:
print("Q4_1_3_data_k = " , A["CourseWork_1"].Q4_1_3_data_k, "\n")
print("Q4_1_3_data_l = " , A["CourseWork_1"].Q4_1_3_data_l, "\n")
print("Q4_1_3_data_m = " , A["CourseWork_1"].Q4_1_3_data_m, "\n")
print("Q4_1_3_data_n = " , A["CourseWork_1"].Q4_1_3_data_n, "\n")

Q4_1_3_data_k = 72
Q4_1_3_data_l = 69
Q4_1_3_data_m = 73
Q4_1_3_data_n = 34


### 3. (b)

In [11]:
A["CourseWork_1"].Q4_1_3_b_ans = true

true

## 4.2. The Matrix of the Linear Map


### 1

In [12]:
A["CourseWork_1"].Q4_2_1_ans = true

true

## 4.3. Adjoint Operator

### 1.(a)

In [80]:
function SubSampl_Op(n,Omega)
    #build an m = Omega.length * n matrix, call it M, which is the linear map
    m = zeros(length(Omega),n)
    #fill in ones in matrix, where M[i,Omega[i]] = 1
    for i in 1:length(Omega)
        m[i,Omega[i]] = 1
    end
    #return the matrix
    return m, transpose(m)
end

A["CourseWork_1"].Q4_3_1_a_ans_Operator , A["CourseWork_1"].Q4_3_1_a_ans_AdjointOperator = 
SubSampl_Op(
    A["CourseWork_1"].Q4_3_1_data_n,
    A["CourseWork_1"].Q4_3_1_data_Omega
    )

([0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 1.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 1.0; 0.0 0.0 … 0.0 0.0])

In [14]:
#print("Q4_3_1_data_n = " , A["CourseWork_1"].Q4_3_1_data_n, "\n")
#print("Q4_3_1_data_Omega = " , A["CourseWork_1"].Q4_3_1_data_Omega, "\n")
#print("Q4_3_1_data_x = " , A["CourseWork_1"].Q4_3_1_data_x, "\n")
#test:
#y = A["CourseWork_1"].Q4_3_1_a_ans_Operator*A["CourseWork_1"].Q4_3_1_data_x
#print(y)

In [15]:
#test:
A["CourseWork_1"].Q4_3_1_a_ans_Operator*A["CourseWork_1"].Q4_3_1_data_x

35-element Vector{Float64}:
 -0.7120263375637099
 -0.3350809296111196
 -0.10569899740463622
 -0.7025129961596984
  1.2830149847033867
 -0.7176318751925367
 -1.1166279172153384
  1.3518746859672155
 -1.2785399384565972
  0.5559971550784112
  ⋮
 -0.2225617304775508
 -0.2588815665080058
 -1.0776861194782485
  0.7674149491198085
 -0.8271655141893217
  0.0850861512165227
  0.8653510720115296
 -1.3106676748148585
  0.050138419750105315

### 1.(b)

In [88]:
function Subsample(x,Omega)
    output = zeros(length(Omega))
    #loop through Omega and fill in y with x[omega[i]]
    for i in 1:length(Omega)
        output[i] = x[Omega[i]]
    end 
    return output
end


#run the function to assign to answer
#Q4_3_1_b_ans_y::Union{Missing,Vector}
A["CourseWork_1"].Q4_3_1_b_ans_y = Subsample(A["CourseWork_1"].Q4_3_1_data_x,A["CourseWork_1"].Q4_3_1_data_Omega)

35-element Vector{Float64}:
 -0.7120263375637099
 -0.3350809296111196
 -0.10569899740463622
 -0.7025129961596984
  1.2830149847033867
 -0.7176318751925367
 -1.1166279172153384
  1.3518746859672155
 -1.2785399384565972
  0.5559971550784112
  ⋮
 -0.2225617304775508
 -0.2588815665080058
 -1.0776861194782485
  0.7674149491198085
 -0.8271655141893217
  0.0850861512165227
  0.8653510720115296
 -1.3106676748148585
  0.050138419750105315

### 1.(c)

In [89]:
function Subsample_adj(y,Omega,n)
    z = zeros(n)
    for i in 1:length(Omega)
        z[Omega[i]] = y[i]
    end
    return z
end

#test:
A["CourseWork_1"].Q4_3_1_c_ans_z = Subsample_adj(A["CourseWork_1"].Q4_3_1_b_ans_y,A["CourseWork_1"].Q4_3_1_data_Omega,A["CourseWork_1"].Q4_3_1_data_n)
#Q4_3_1_c_ans_z::Union{Missing,Vector}



90-element Vector{Float64}:
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
 -0.7120263375637099
 -0.3350809296111196
  0.0
  0.0
  ⋮
  0.0
  0.0
  0.0850861512165227
  0.8653510720115296
  0.0
  0.0
 -1.3106676748148585
  0.050138419750105315
  0.0

### 2.(a)

In [18]:
function Q4_3_2_a_ans(p, q)

    output = zeros(p*q,p+q-1)
    output_adj = zeros(p+q-1,p*q)
    m = 1

    for i in 1:q
        for j in 1:p
            output[m,i+j-1] = 1 #fill in ones into operator accordingly
            m+=1 
        end
    end

    return output, transpose(output)
end


#assign to answer
A["CourseWork_1"].Q4_3_2_a_ans_Operator, A["CourseWork_1"].Q4_3_2_a_ans_AdjointOperator = 
Q4_3_2_a_ans(
    A["CourseWork_1"].Q4_3_2_data_p,
    A["CourseWork_1"].Q4_3_2_data_q
)
#Q4_3_2_a_ans_AdjointOperator::Union{Missing,Matrix}


([1.0 0.0 … 0.0 0.0; 0.0 1.0 … 0.0 0.0; … ; 0.0 0.0 … 1.0 0.0; 0.0 0.0 … 0.0 1.0], [1.0 0.0 … 0.0 0.0; 0.0 1.0 … 0.0 0.0; … ; 0.0 0.0 … 1.0 0.0; 0.0 0.0 … 0.0 1.0])

In [19]:
#test the operator
vect = A["CourseWork_1"].Q4_3_2_a_ans_Operator*A["CourseWork_1"].Q4_3_2_data_x
m = vect[:,:]
reshape(m,63,93)
#looking good

63×93 Matrix{Float64}:
 -0.703016    0.767841    0.391556   …  -0.0652388  -1.13269   -1.02731
  0.767841    0.391556    2.06689       -1.13269    -1.02731   -0.869131
  0.391556    2.06689    -0.381678      -1.02731    -0.869131   2.03767
  2.06689    -0.381678   -0.39857       -0.869131    2.03767    0.231659
 -0.381678   -0.39857     0.479802       2.03767     0.231659   0.779107
 -0.39857     0.479802   -2.06458    …   0.231659    0.779107  -2.85532
  0.479802   -2.06458     0.311218       0.779107   -2.85532    1.61624
 -2.06458     0.311218   -1.60753       -2.85532     1.61624    0.888969
  0.311218   -1.60753    -0.408357       1.61624     0.888969  -0.488583
 -1.60753    -0.408357    0.151226       0.888969   -0.488583   0.645388
  ⋮                                  ⋱   ⋮                     
  2.68556    -0.721596    1.71901       -0.102503    0.968977  -0.629898
 -0.721596    1.71901    -1.97256    …   0.968977   -0.629898  -0.592585
  1.71901    -1.97256    -0.299998      -

In [20]:
#make vector x first
vect_x = A["CourseWork_1"].Q4_3_2_data_x

#make a vector y for testing
vect_y = vect_x

#transform them individually
vect_y_transform = A["CourseWork_1"].Q4_3_2_a_ans_Operator*vect_y
vect_x_transform = A["CourseWork_1"].Q4_3_2_a_ans_Operator*vect_x

#take inner product
transpose(vect_x_transform)*vect_y_transform

#6850.4006511862335

6850.4006511862335

In [21]:
#now, test the original vector x times adjoint transform of transformed y
vect_y_adj = A["CourseWork_1"].Q4_3_2_a_ans_AdjointOperator*vect_y_transform
vect_y_adj

#6850.4006511862335

155-element Vector{Float64}:
  -0.7030158807938457
   1.535682022686232
   1.1746691120748582
   8.267564946627187
  -1.9083909219122193
  -2.3914211218080244
   3.3586156917812717
 -16.51667312175439
   2.800960902327336
 -16.07525425093906
   ⋮
  -5.6690849450876035
  -4.740682869063179
  -6.677637220012744
  10.0215198055596
  -7.574875373889979
   8.414598040735248
  -0.6273441973984029
   3.0707426937953914
  -2.1585486519157375

### 2.(b)

In [22]:
function Q4_3_2_b(p,q,x)
    H = zeros(p*q,1)
    idx = 1
    for i in 1:q
      for j in 1:p
        H[idx] = x[i+j-1]
        idx += 1 
      end
    end
    return reshape(H,p,q)
end

#Q4_3_2_b_ans_H::Union{Missing,Matrix}
A["CourseWork_1"].Q4_3_2_b_ans_H = Q4_3_2_b(
    A["CourseWork_1"].Q4_3_2_data_p,
    A["CourseWork_1"].Q4_3_2_data_q,
    A["CourseWork_1"].Q4_3_2_data_x
)



63×93 Matrix{Float64}:
 -0.703016    0.767841    0.391556   …  -0.0652388  -1.13269   -1.02731
  0.767841    0.391556    2.06689       -1.13269    -1.02731   -0.869131
  0.391556    2.06689    -0.381678      -1.02731    -0.869131   2.03767
  2.06689    -0.381678   -0.39857       -0.869131    2.03767    0.231659
 -0.381678   -0.39857     0.479802       2.03767     0.231659   0.779107
 -0.39857     0.479802   -2.06458    …   0.231659    0.779107  -2.85532
  0.479802   -2.06458     0.311218       0.779107   -2.85532    1.61624
 -2.06458     0.311218   -1.60753       -2.85532     1.61624    0.888969
  0.311218   -1.60753    -0.408357       1.61624     0.888969  -0.488583
 -1.60753    -0.408357    0.151226       0.888969   -0.488583   0.645388
  ⋮                                  ⋱   ⋮                     
  2.68556    -0.721596    1.71901       -0.102503    0.968977  -0.629898
 -0.721596    1.71901    -1.97256    …   0.968977   -0.629898  -0.592585
  1.71901    -1.97256    -0.299998      -

### 2.(c)

In [23]:
function Q4_3_2_c(p,q,H)
    
    output = zeros(p+q-1)
    minpq = min(p,q)


    #collect each term in matrixx Q4_3_2_b_ans_H
    v = zeros(p+q-1)
    for i in 1:p
        v[i] = H[i,1]
    end
    for i in 1:q-1
        v[p+i] = H[p,i+1]
    end

    help = zeros(p+q-1)
    for i in 1:minpq
        help[i] = i
        help[p+q-i] = i
    end
    for i in minpq+1:p+q-minpq
        help[i] = minpq
    end

    j = 0
    for i in 1:p+q-1
        output[i] = v[i] * help[i]
    end


    return output
end

A["CourseWork_1"].Q4_3_2_c_ans_z = Q4_3_2_c(
    A["CourseWork_1"].Q4_3_2_data_p,
    A["CourseWork_1"].Q4_3_2_data_q,
    A["CourseWork_1"].Q4_3_2_b_ans_H
)

#Q4_3_2_c_ans_z::Union{Missing,Vector}


155-element Vector{Float64}:
  -0.7030158807938457
   1.535682022686232
   1.1746691120748582
   8.267564946627187
  -1.9083909219122193
  -2.3914211218080244
   3.3586156917812717
 -16.51667312175439
   2.800960902327336
 -16.075254250939064
   ⋮
  -5.6690849450876035
  -4.740682869063179
  -6.677637220012743
  10.021519805559603
  -7.574875373889979
   8.414598040735248
  -0.6273441973984029
   3.0707426937953914
  -2.1585486519157375

In [24]:
A["CourseWork_1"].Q4_3_2_c_ans_z - vect_y_adj

155-element Vector{Float64}:
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
 -3.552713678800501e-15
  ⋮
  0.0
  0.0
  8.881784197001252e-16
  1.7763568394002505e-15
  0.0
  0.0
  0.0
  0.0
  0.0

### 2.(d)

In [25]:
A["CourseWork_1"].Q4_3_2_d_ans = A["CourseWork_1"].Q4_3_2_c_ans_z ./ A["CourseWork_1"].Q4_3_2_data_x


#Q4_3_2_d_ans::Union{Missing,Vector}

155-element Vector{Float64}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0
  ⋮
  9.0
  8.0
  7.0
  6.000000000000001
  5.0
  4.0
  3.0000000000000004
  2.0
  1.0

### 3.(a)

In [26]:
function Convolution(x,h)
    n=length(x)
    m=length(h)
    C_h=zeros(n+m-1,n)
    for i in 1:(n+m-1)
        for j in 1:n
            if i-j>=0 && i-j<m
                C_h[i,j]=h[i-j+1]
            end
        end
    end
    C_star=transpose(C_h)
    return C_h,C_star
end
A["CourseWork_1"].Q4_3_3_a_ans_Operator,A["CourseWork_1"].Q4_3_3_a_ans_AdjointOperator=Convolution(A["CourseWork_1"].Q4_3_3_data_x,A["CourseWork_1"].Q4_3_3_data_h)

([1.3824927555505953 0.0 … 0.0 0.0; -0.5103166046164548 1.3824927555505953 … 0.0 0.0; … ; 0.0 0.0 … -0.5954076268360049 1.4418340630763695; 0.0 0.0 … 0.0 -0.5954076268360049], [1.3824927555505953 -0.5103166046164548 … 0.0 0.0; 0.0 1.3824927555505953 … 0.0 0.0; … ; 0.0 0.0 … -0.5954076268360049 0.0; 0.0 0.0 … 1.4418340630763695 -0.5954076268360049])

### 3.(b)

In [27]:
function find3by(x,h)
    n=length(x)
    m=length(h)
    y=zeros(n+m-1)
    for t in 1:n+m-1
        for tau in max(1,t+1-n):min(t,m,n)
            y[t]+=x[t+1-tau]*h[tau]
        end
    end
    return y
end
A["CourseWork_1"].Q4_3_3_b_ans_y=find3by(A["CourseWork_1"].Q4_3_3_data_x,A["CourseWork_1"].Q4_3_3_data_h)

30-element Vector{Float64}:
  0.34718847379108875
 -1.2037466115407542
  1.2143237704132197
 -0.8471708509259193
  0.21167344856642728
  3.2408012713515277
  0.6000918278214773
  0.5409199682492275
  2.3811466674810604
 -2.2237756862166327
  ⋮
 -0.022969189555171243
 -2.9153057871158228
  1.1226247740081816
 -2.280458054916075
  0.8419779301022432
 -3.2712458940538798
  1.8311920634633472
 -0.5352228267139241
 -0.04900675846325167

### 3.(c)

In [28]:
function find3cz(y,h)
    m=length(h)
    n=length(y)-m+1
    z=zeros(n)
    for t in 1:n
        for tau in 1:m
            z[t]+=y[t+tau-1]*h[tau]
        end
    end
    return z
end
Z_free = A["CourseWork_1"].Q4_3_3_c_ans_z=find3cz(A["CourseWork_1"].Q4_3_3_b_ans_y,A["CourseWork_1"].Q4_3_3_data_h)

17-element Vector{Float64}:
  -0.6694613947132696
  -6.8800835916907275
   6.003516101366196
   7.916746540405512
 -10.370132093904317
  32.10665575363984
   5.597247955218237
   2.0833467022322765
   0.9979008161259771
  10.99806129575536
 -19.316733749680562
  21.927495498115704
  -6.660649428009175
   8.339631950670569
 -18.033903348795953
  20.5098866386054
 -17.519123657614617

### 4.(a)

In [76]:
function Cyclic(x,h)
    n=length(x)
    C_h=zeros(n,n)
    for i in 1:n
        for j in 1:n
            k=i+1-j
            if k<=0
                k=n+k
            end
            C_h[i,k]=h[j]
        end
    end
    C_star=transpose(C_h)
    return C_h,C_star 
end
A["CourseWork_1"].Q4_3_4_a_ans_Operator,A["CourseWork_1"].Q4_3_4_a_ans_AdjointOperator=Cyclic(A["CourseWork_1"].Q4_3_4_data_x,A["CourseWork_1"].Q4_3_4_data_h)

([0.9500237407025717 2.2523378283132285 … -0.3355742560381149 -1.252622449487755; -1.252622449487755 0.9500237407025717 … -1.0779405511934164 -0.3355742560381149; … ; -0.7442819493207524 -0.5762169532073635 … 0.9500237407025717 2.2523378283132285; 2.2523378283132285 -0.7442819493207524 … -1.252622449487755 0.9500237407025717], [0.9500237407025717 -1.252622449487755 … -0.7442819493207524 2.2523378283132285; 2.2523378283132285 0.9500237407025717 … -0.5762169532073635 -0.7442819493207524; … ; -0.3355742560381149 -1.0779405511934164 … 0.9500237407025717 -1.252622449487755; -1.252622449487755 -0.3355742560381149 … 2.2523378283132285 0.9500237407025717])

### 4.(b)

In [30]:
import DSP
function find4by(x,h)
    n=length(x)
    y=zeros(n)
    x_ex=repeat(x, outer=(3,))
    y=DSP.conv(x_ex,h)
    y_ans=y[n+1:2n]
    return y_ans
end
A["CourseWork_1"].Q4_3_4_b_ans_y = find4by(A["CourseWork_1"].Q4_3_4_data_x,A["CourseWork_1"].Q4_3_4_data_h)

142-element Vector{Float64}:
  -0.6505373784033195
  17.62741253034949
  -0.16099701667292926
  15.91581493269945
  13.078120412775444
  11.240466792931896
 -20.39868062058624
   0.2816123254526924
  -3.172618311774635
   0.32601355043535385
   ⋮
  -4.4971743585573565
  -8.75309808871373
   9.650725697430005
 -15.844227065531346
   3.893551011069385
  -2.552353170774595
   6.962053168975658
  -9.103331523740948
 -13.93975454296985

### 4.(c)

In [31]:
function find4cz(y,h)
    n=length(y)
    z=zeros(n)
    h=reverse(h)
    h_ex=repeat(h, outer=(3,))
    z=DSP.conv(y,h_ex)
    z_ans=z[n:2n-1]
    return z_ans
end
A["CourseWork_1"].Q4_3_4_c_ans_z=find4cz(A["CourseWork_1"].Q4_3_4_b_ans_y,A["CourseWork_1"].Q4_3_4_data_h)

142-element Vector{Float64}:
 -285.4178889536644
 -213.8557786586268
   20.825571705360137
  115.47778899008901
   61.440398215620576
 -364.2334472579603
   34.18014406875943
   50.06381340742321
  -65.00215441817535
  189.2023532884148
    ⋮
 -188.01254045179405
   67.43031876578027
   89.61976611092582
  -94.09717466451669
 -227.05493821917602
  300.42608973802515
    8.141598775171197
 -225.03428107948713
 -568.3838990156075

### 5.(a)

In [21]:
import FFTW
function MRI(x,omega)
    m,n=size(x)
    O1= FFTW.fft(x)
    O2= FFTW.fftshift(O1)
    O3= zeros(ComplexF64,m,n)
    for i in 1:m
        for j in 1:n
            if omega[i,j]==1
                O3[i,j]=O2[i,j]
            end
        end
    end
    O3=vec(O3)
    return O1,O2,O3
end
A["CourseWork_1"].Q4_3_5_a_ans_O1,A["CourseWork_1"].Q4_3_5_a_ans_O2,A["CourseWork_1"].Q4_3_5_a_ans_O3=MRI(A["CourseWork_1"].Q4_3_5_data_X,A["CourseWork_1"].Q4_3_5_data_Omega)

(ComplexF64[7991.164705882353 + 0.0im -3910.3010220423803 - 118.45124788344212im … -973.8855047234892 + 141.34581545030696im -3910.3010220423803 + 118.45124788344212im; -2637.6352164198715 - 414.0041161037336im 957.7537395017742 + 94.45223731386422im … 798.124782536756 + 307.38513700791464im 793.0829983834138 - 53.28594654502898im; … ; -1043.7904716544533 + 361.30523924569184im 737.0745236966186 - 278.1445179789142im … 160.3770987030368 - 54.3496634065702im 669.8075516813126 - 205.11240051499183im; -2637.6352164198715 + 414.0041161037336im 793.0829983834138 + 53.28594654502898im … 787.9458401059704 - 479.0693778240184im 957.7537395017742 - 94.45223731386422im], ComplexF64[33.17647058823525 + 0.0im -20.304382996097743 - 2.547913451843277im … 13.218450597843688 + 9.53767103916979im -20.304382996097743 + 2.547913451843277im; 1.1761498993100856 - 14.410057649895519im 9.175202157078726 + 17.212898158882485im … 56.94905777747435 - 47.62593481259198im -48.806498188098516 + 38.4589659098732im;

In [23]:
A["CourseWork_1"].Q4_3_5_a_ans_O2

64×64 Matrix{ComplexF64}:
   33.1765+0.0im       -20.3044-2.54791im   …   -20.3044+2.54791im
   1.17615-14.4101im     9.1752+17.2129im       -48.8065+38.459im
  -20.7767-19.3239im    13.9881+22.7189im        15.2606+12.4334im
  -28.0664+33.5859im  -0.845422-9.05155im         37.214-16.0234im
   32.2943+39.2859im   -23.8243-10.4293im        31.8874-16.3302im
   32.0808-46.5427im   -16.0245+24.8986im   …   -5.03033+10.7977im
 -0.757764-37.5057im    60.6989-8.79246im       -51.9326-0.272931im
  -52.9163-9.482im     0.242136+14.1726im       -3.49592+12.7333im
  -6.82045+33.3238im   -16.9439-6.30018im        51.5543-13.2841im
 -0.326936+25.2069im    -7.8674-33.7087im        9.64384-15.6537im
          ⋮                                 ⋱  
 -0.326936-25.2069im    9.64384+15.6537im   …    -7.8674+33.7087im
  -6.82045-33.3238im    51.5543+13.2841im       -16.9439+6.30018im
  -52.9163+9.482im     -3.49592-12.7333im       0.242136-14.1726im
 -0.757764+37.5057im   -51.9326+0.272931im       60.698

### 5.(b)

In [24]:
import FFTW
function IvMRI(y,omega)
    m,n=size(omega)
    O1=reshape(y,m,n)
    O2=FFTW.ifftshift(O1)
    O3=FFTW.ifft(O2)
    return O1,O2,O3
end
A["CourseWork_1"].Q4_3_5_b_ans_O1,A["CourseWork_1"].Q4_3_5_b_ans_O2,A["CourseWork_1"].Q4_3_5_b_ans_O3=IvMRI(A["CourseWork_1"].Q4_3_5_a_ans_O3,A["CourseWork_1"].Q4_3_5_data_Omega)

(ComplexF64[0.0 + 0.0im 0.0 + 0.0im … 0.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im … 0.0 + 0.0im 0.0 + 0.0im; … ; 0.0 + 0.0im 0.0 + 0.0im … 0.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im … 0.0 + 0.0im 0.0 + 0.0im], ComplexF64[0.0 + 0.0im 0.0 + 0.0im … 0.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im … 0.0 + 0.0im 0.0 + 0.0im; … ; 0.0 + 0.0im 0.0 + 0.0im … 0.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im … 0.0 + 0.0im 0.0 + 0.0im], ComplexF64[2.255140518769849e-16 + 2.0122792321330962e-16im -4.644782429379226e-18 + 9.712748595216184e-17im … 1.1478712669902975e-16 + 2.4177782532121835e-17im -8.573952893499919e-17 + 2.1693249916432995e-17im; 1.8388068845354155e-16 + 1.0928757898653885e-16im 1.5839194818615776e-16 + 2.1058684187257736e-17im … 1.732760322957228e-17 - 1.5680042089034587e-17im 1.199917696041167e-16 - 3.2370010532625794e-17im; … ; -0.0035485958710392528 + 0.005846900419560241im 0.0037633025336726105 - 0.0036305071681237274im … -0.003357022455418664 - 0.000297847632421272

## 5.1. The Netflix Problem

### 1.(a)

In [190]:
function update_V(y, Omega, U)
    #Let the operator matrix be M (which is actually the observation matrix)
    m , n = size(Omega)
    r = size(U,2)
    k = 1   #for incrementing through y
    #initialize output
    V_new = zeros(r,n)
    
    #NOTE: m = height of m, n = height of V
    for j in 1:n    #along each column of omega same column = same v
        M_temp = zeros(1,r)
        little_y = vec([])
        for i in 1:m        #along each row of omega
            if Omega[i,j] == 1
                append!(little_y, y[k])
                M_temp = [M_temp;U[i,:]']
                k+=1
            end
        end
        M_temp = M_temp[2:end,:]
        V_col = (inv(M_temp'M_temp))* M_temp' * little_y 
        V_new[:,j] = V_col
    end

    return V_new'
end




    A["CourseWork_1"].Q5_1_a_ans_V = 
    update_V(
        A["CourseWork_1"].Q5_1_data_y,
        A["CourseWork_1"].Q5_1_data_Omega,
        A["CourseWork_1"].Q5_1_data_Uini
    )



ArgumentError: ArgumentError: number of columns of each array must match (got (10, 458))

### 1.(b)

In [195]:
function update_U(y, Omega, V)
    #Let the operator matrix be M (which is actually the observation matrix)
    m , n = size(Omega)
    r = size(V,2)
    V = V'  #make v easier to work on
    #initialize output
    U_new = zeros(m,r)

    #reshape y because we are workign on a different index

    
    #NOTE: m = height of m, n = height of V
    for i in 1:m    
        M_temp = zeros(r,1)
        little_y = vec([])
        for j in 1:n        
            if Omega[i,j] == 1
                idx = sum(Omega[:,1:n-1]) + sum(Omega[1:m,n])
                append!(little_y, y[idx])
                #M_temp = [M_temp:V[:,j]]
                #k+=1
            end
        end
        #M_temp = M_temp[2:end,:]
        #V_col = (inv(M_temp'M_temp))* M_temp' * little_y 
        #V_new[:,j] = V_col
    end

    
    
    return 
end




    #A["CourseWork_1"].Q5_1_b_ans_U= 
    update_U(
        A["CourseWork_1"].Q5_1_data_y,
        A["CourseWork_1"].Q5_1_data_Omega,
        A["CourseWork_1"].Q5_1_a_ans_V
    )



### 1.(c)

In [ ]:

function alternating_minimization(num_iterations, U0, y, Omega, rank_X)
    U_i = U0
    # Dimensions of U0
    m, r = size(U0)
    

    # Initialize V with random values (you can adjust this)
    V_i = randn(r, size(Omega, 2))
    
    
    for i in 1:num_iterations
        V_i = update_V(U_i, y, Omega, rank_X)
        U_i = update_U(U_i, V_i, y, Omega, rank_X)
    end
    #print("check")
    return U_i * V_i
end
other_y= alternating_minimization(10,U_ini,y,subsampling_operator,10)
observed_values = other_y[indices]
observed_vector = Vector(observed_values)
println(observed_vector)
println(observed_values)
#print(U_ini-new_U)
#println(observed_vector)

## 5.2. Estimation Accuracy

### 1.(a)

### 1.(c)

### 1.(b)

## 5.3. LS Recovery from Convolution

### 1.(a)

In [106]:
function find_Ab(y, h, Omega, alpha, n)
    #NOTE: dimension of x is n, which is the same as h
    #define our output
    A = zeros(n,n)
    b = zeros(n)
    #dummy varialbe x for getting cyclic convolution operator
    x = zeros(n)
    C1, C1_adj = Cyclic(x,h)
    S1, S1_adj = SubSampl_Op(n, Omega)
    #M is the overall operator on x
    M = S1 * C1

    A = transpose(M) * M - alpha * Matrix(I, n, n)
    b = - transpose(y) * M

    return A, transpose(b)
     
end

A["CourseWork_1"].Q5_3_1_a_ans_A, A["CourseWork_1"].Q5_3_1_a_ans_b = find_Ab(
    A["CourseWork_1"].Q5_3_data_y,
    A["CourseWork_1"].Q5_3_data_h,
    A["CourseWork_1"].Q5_3_data_Omega, 
    A["CourseWork_1"].Q5_3_data_alpha, 
    A["CourseWork_1"].Q5_3_data_n)


#Q5_3_1_a_ans_A
#Q5_3_1_a_ans_b

([58.58295690708637 16.749593606704543 … -8.543642336511715 2.944019978314911; 16.749593606704543 81.97414348242744 … -1.7888451225898336 3.382344204571132; … ; -8.543642336511715 -1.7888451225898336 … 70.1371201046607 11.802724893187971; 2.944019978314911 3.382344204571132 … 11.802724893187971 52.156062838153986], [-69.53828854742798, -173.70282395222205, 68.02940717907882, 87.82656217754106, 105.01011580268937, -82.29628114500485, 27.990285549601616, 35.80108482638736, 47.63359426380435, -90.44024974873224  …  51.964166381064956, 22.13599268170875, -36.48992152928214, -11.505692973005765, -194.32868159388516, -116.12801383503677, 26.703281592845098, 117.11984970259122, 122.38418026362703, -98.38141712432262])

### 1(b)

In [112]:
A["CourseWork_1"].Q5_3_1_b_ans_x = A["CourseWork_1"].Q5_3_1_a_ans_A\A["CourseWork_1"].Q5_3_1_a_ans_b

135-element Vector{Float64}:
  0.34094877180210825
 -0.8600716274528826
  0.12798927500187035
  0.21133650441099414
  0.8267088419110429
 -0.539878594671811
 -0.09827220205722605
 -0.11154584086027951
 -0.18505371860852823
 -0.2077749308133293
  ⋮
  0.6250567685259288
  0.15620810996582782
 -0.43565782549336235
 -1.2888760234481316
 -0.4316232712678664
  0.2884048284631091
  1.2279036271681685
  0.6660082123597082
 -0.43378982909887603

### 2.(a)

In [108]:
function mat_free_uAv(u,v,y,h,Omega,alpha,n)
    #uAv is basically:
    #u' * cyc_conv * subsamp * sub_sam * cyc_conv * v - alpha * u * v
    # or: u' * h' * P_Omega' * P_Omega * h * v - alpha *u' * v

    #get h*v
    Hv = zeros(n) 
    Hv = find4by(h,v)       #call function in 4.4
    #get Phv
    PHv = Subsample(Hv, Omega)      #call function in 4.1
    #get PtPhv
    PtPHv = Subsample_adj(PHv,Omega,n)  #call function in 4.1
    #get htPtPhv
    HtPtPHv = find4cz(PtPHv,h)      #call function in 4.4 
    #get uHtPtPhv
    uHtPtPhv = u' * HtPtPHv
    #get alpha * u * v
    ualphav = alpha * u' *v
    uAv = uHtPtPhv - ualphav  

    return uAv
end

function mat_free_bu(u,y,h,Omega,n)
    #bu = -y' * P * H * u
    
    #we apply each operators in function form one by one
    Hu = find4by(h,u)
    PHu = Subsample(Hu, Omega)
    
    #then multiply by y
    yPHu = y'*PHu

    bu = -yPHu
    return bu
end

# Assign to answer
A["CourseWork_1"].Q5_3_2_a_ans_uAv = 
mat_free_uAv(
     A["CourseWork_1"].Q5_3_data_u,
     A["CourseWork_1"].Q5_3_data_v,
     A["CourseWork_1"].Q5_3_data_y,
     A["CourseWork_1"].Q5_3_data_h,
     A["CourseWork_1"].Q5_3_data_Omega,
     A["CourseWork_1"].Q5_3_data_alpha,
     A["CourseWork_1"].Q5_3_data_n
 )

 A["CourseWork_1"].Q5_3_2_a_ans_bu = 
 mat_free_bu(
     A["CourseWork_1"].Q5_3_data_u,
     A["CourseWork_1"].Q5_3_data_y,
     A["CourseWork_1"].Q5_3_data_h,
     A["CourseWork_1"].Q5_3_data_Omega,
     A["CourseWork_1"].Q5_3_data_n
 )

#Q5_3_2_a_ans_uAv
#Q5_3_2_a_ans_bu


-650.0147060148207

### 2.(b)

In [111]:
function iterate_solve(A,b)

    
    Op = LinearOperators.LinearOperator(A)  
    x = cg(Op, b)
    return x
     
end

A["CourseWork_1"].Q5_3_2_b_ans_x = 
iterate_solve(
    A["CourseWork_1"].Q5_3_1_a_ans_A,
    A["CourseWork_1"].Q5_3_1_a_ans_b
)

135-element Vector{Float64}:
  0.3409487692315657
 -0.8600716162927828
  0.12798926967868604
  0.2113365094192934
  0.8267088344229716
 -0.5398785913997967
 -0.09827221197580181
 -0.11154584656995407
 -0.18505373317293858
 -0.20777493191484575
  ⋮
  0.6250567739989742
  0.15620811310518012
 -0.43565782910179107
 -1.2888760206058443
 -0.4316232618307871
  0.28840482745417334
  1.2279036230756923
  0.6660082036887459
 -0.43378983608705834

## 5.4. LS Recovery for MRI

### 1.(a)

135-element Vector{Float64}:
 -0.3409487692315657
  0.8600716162927828
 -0.12798926967868604
 -0.2113365094192934
 -0.8267088344229716
  0.5398785913997967
  0.09827221197580181
  0.11154584656995407
  0.18505373317293858
  0.20777493191484575
  ⋮
 -0.6250567739989742
 -0.15620811310518012
  0.43565782910179107
  1.2888760206058443
  0.4316232618307871
 -0.28840482745417334
 -1.2279036230756923
 -0.6660082036887459
  0.43378983608705834

### 1.(b)