# Coursework 2

### PLAGIARISM/COLLUSION DECLARATION

 

Coursework submitted for assessment must be the original work of you and your group. Assignments are subjected to regular checks for plagiarism and/or collusion. Plagiarism is the presentation of another person’s thoughts or words (those outside your group) as if they were your own. Collusion involves obtaining help from someone outside your group to complete your work. In preparing your coursework, you should not seek help, or copy from any other person or source, including the

Internet, without proper and explicit acknowledgement.

 

There is a procedure in place for you to declare individual contributions within your group for courswork. You must declare the contributions fairly and accurately.

 

You must not disclose your solutions or insights related to coursework with anyone else, including future students or the Internet.

 

By acknowledging the the statements above, you are declaring that both this and all subsequent pieces of coursework are, and will remain, the original work of you and your group.

 

* Submissions will not be accepted without the aforementioned declaration.

 

* Members of a group are deemed to have collective responsibility for the integrity for work submitted and are liable for any penalty imposed, proportionate to their contributions.

In [1]:
using JLD2,FileIO
using LinearAlgebra
using Wavelets
using FFTW

In [2]:
# Run this code before you start doing the coursework

Base.@kwdef mutable struct CourseWork_1
    
    CID::Int
    Plagiarism_declare::Union{Missing,Bool}
    Demo_willing::Union{Missing,Bool}
    
    # 6.1 Proximal Operator
    
    Q6_1_a_data_A::Matrix
    Q6_1_a_data_b::Vector
    Q6_1_a_data_z::Vector
    Q6_1_a_data_gamma::Float64
    
    Q6_1_a_ans_x::Union{Missing,Vector}
    
    Q6_1_b_data_z::Vector
    Q6_1_b_data_a::Float64
    Q6_1_b_data_b::Float64
    Q6_1_b_data_gamma::Float64
    
    Q6_1_b_ans_x::Union{Missing,Vector}
    
    Q6_1_c_data_z::Vector
    Q6_1_c_data_k::Int
    Q6_1_c_data_gamma::Float64
    
    Q6_1_c_ans_x::Union{Missing,Vector}
    
    Q6_1_d_data_z::Vector
    Q6_1_d_data_gamma::Float64
    
    Q6_1_d_ans_x::Union{Missing,Vector}
    
    Q6_1_e_data_Z::Matrix
    Q6_1_e_data_r::Int
    Q6_1_e_data_gamma::Float64
    
    Q6_1_e_ans_X::Union{Missing,Matrix}
    
    Q6_1_f_data_Z::Matrix
    Q6_1_f_data_gamma::Float64
    
    Q6_1_f_ans_X::Union{Missing,Matrix}
    
    Q6_1_g_data_Z::Matrix
    Q6_1_g_data_gamma::Float64
    
    Q6_1_g_ans_X::Union{Missing,Matrix}
    
    Q6_1_h_data_z::Vector
    Q6_1_h_data_gamma::Float64
    
    Q6_1_h_ans_x::Union{Missing,Vector}
    
    # 6.2 Proximal operators related to ℓ1-norm
    
    Q6_2_a_data_z::Vector
    Q6_2_a_data_gamma::Float64
    Q6_2_a_data_lambda::Float64
    
    Q6_2_a_ans_x::Union{Missing,Vector}
    
    Q6_2_b_data_z::Vector
    Q6_2_b_data_a::Vector
    Q6_2_b_data_gamma::Float64
    Q6_2_b_data_lambda::Float64
    
    Q6_2_b_ans_x::Union{Missing,Vector}
    
    Q6_2_c_data_z::Vector
    Q6_2_c_data_U::Matrix
    Q6_2_c_data_gamma::Float64
    Q6_2_c_data_lambda::Float64
    
    Q6_2_c_ans_x::Union{Missing,Vector}
    
    Q6_2_d_data_z::Vector
    Q6_2_d_data_U::Matrix
    Q6_2_d_data_gamma::Float64
    Q6_2_d_data_lambda::Float64
    
    Q6_2_d_ans_x::Union{Missing,Vector}
    
    # 7.1 Greedy Algorithms
    
    Q7_1_1_data_y::Vector
    Q7_1_1_data_A::Matrix
    Q7_1_1_data_S::Int
    
    Q7_1_1_ans_x::Union{Missing,Vector}
    
    Q7_1_2_data_y::Vector
    Q7_1_2_data_A::Matrix
    Q7_1_2_data_S::Int
    
    Q7_1_2_ans_x::Union{Missing,Vector}
    
    Q7_1_3_data_y::Vector
    Q7_1_3_data_A::Matrix
    Q7_1_3_data_S::Int
    
    Q7_1_3_ans_x::Union{Missing,Vector}
    
    # 7.2 Proximal Gradient Method
    
    Q7_2_1_data_z::Vector
    Q7_2_1_data_xini::Vector
    Q7_2_1_data_A::Matrix
    Q7_2_1_data_lambda::Float64
    Q7_2_1_data_gamma::Float64
    
    Q7_2_1_ans_xhat::Union{Missing,Vector}
    Q7_2_1_ans_subgradient::Union{Missing,Vector}
    
    Q7_2_2_data_z::Vector
    Q7_2_2_data_A::Matrix
    Q7_2_2_data_lambda::Float64
    
    Q7_2_2_ans_objfun::Union{Missing,Vector}
    
    # 7.3 MRI CS Recovery: Wavelet
    
    Q7_3_1_data_X0::Matrix
    Q7_3_1_data_Omega::Matrix
    Q7_3_1_data_y::Vector
    
    Q7_3_1_ans_gradient::Union{Missing,Matrix}
    
    Q7_3_2_data_lambda::Float64
    
    Q7_3_2_ans_X1::Union{Missing,Matrix}
    
    Q7_3_3_ans_X::Union{Missing,Matrix}
    
    # 7.4 MRI CS Recovery: DCT
    
    Q7_4_1_data_X0::Matrix
    Q7_4_1_data_Omega::Matrix
    Q7_4_1_data_y::Vector
    Q7_4_1_data_lambda::Float64
    
    Q7_4_1_ans_X1::Union{Missing,Matrix}
    
    Q7_4_2_ans_X::Union{Missing,Matrix}
    
    # 7.5 MRI CS Recovery: Wavelet and DCT
    
    Q7_5_1_data_Z1::Matrix
    Q7_5_1_data_Z2::Matrix
    Q7_5_1_data_Omega::Matrix
    Q7_5_1_data_y::Vector
    Q7_5_1_data_lambda::Float64
    Q7_5_1_data_alpha::Float64
    
    Q7_5_1_ans_X1::Union{Missing,Matrix}
    
    Q7_5_2_ans_Z1::Union{Missing,Matrix}
    Q7_5_2_ans_Z2::Union{Missing,Matrix}
    
    Q7_5_3_ans_X::Union{Missing,Matrix}
    
end

CourseWork_1

In [3]:
# Download and upload data from JLD file, refer to https://juliaio.github.io/JLD2.jl/dev/
# Example
A = JLD2.load("Laurie Johnston1705019StudentFile.jld2");
A = A[ "CourseWork_1" ];
A.Demo_willing = true;


In [4]:
jldopen("Laurie Johnston1705019StudentFile.jld2", "w") do file
    write(file, "CourseWork_1", A)
  end

## 6.1. Proximal Operator


### 1. (a)

In [5]:
# save your answers in Q6_1_a_ans_x
function Q6_11a() 

### 1. (b)

In [6]:
# save your answers in Q6_1_b_ans_x


### 1. (c)

In [7]:
# save your answers in Q6_1_c_ans_x

### 1. (d)

### 1. (e)

### 1. (f)

### 1. (g)

### 1. (h)

### 2. (a)

### 2. (b)

### 2. (c)

### 2. (d)

In [4]:
z = A.Q6_2_d_data_z
U = A.Q6_2_d_data_U
gamma = A.Q6_2_d_data_gamma
lambda = A.Q6_2_d_data_lambda

# using the solution from this derivation online: https://math.stackexchange.com/questions/1961888/the-proximal-operator-of-the-l-1-norm-function 
x = U' * ((sign.(U*z) .* max.((abs.(U*z) .- (lambda * gamma)), 0.0)))

# print error and have a look
error = (lambda * norm((U*x), 1)) + ((1/(2*gamma)) * (norm((x-z), 2)^2)) 
println(error)

A.Q6_2_d_ans_x = x


20.59085435909057


79-element Vector{Float64}:
  0.11052396078981683
  0.02875737355864877
  0.548789287952911
  0.13625115850632505
  0.14117161960855523
  0.5263854023376945
 -0.12501025719301243
  0.23422593606574585
  0.2368096015062915
  0.2997571026356275
  ⋮
  0.21271413665570807
  0.2539108947616978
  0.25975321348498603
  0.2801926861300879
 -0.004294691130390944
 -0.017858778994156013
  0.18357328574437531
  0.03360353951856539
 -0.04815135142295193

## 7.1. Greedy Algorithms

### 1

### 2

### 3

## 7.2. Proximal Gradient Method

### 1

### 2

### 3

## 7.3. MRI CS Recovery: Wavelet

### 1

In [8]:
# function MRI(x,omega)
#     m,n=size(x)
#     O1= fft(x)
#     O2= fftshift(O1)
#     O3= zeros(ComplexF64,m,n)
#     for i in 1:m
#         for j in 1:n
#             if omega[i,j]==1
#                 O3[i,j]=O2[i,j]
#             end
#         end
#     end
#     O3=vec(O3)
#     O3 = filter(x -> x != 0, vec(O3))
#     return O1,O2,O3
# end

# function IvMRI(y,omega)
#     m,n=size(omega)

#     vec_omega = vec(omega)
#     O1 = complex(Array{Float64}(undef, length(vec_omega)))
#     j = 1
#     for i in 1:length(vec_omega)
#         if vec_omega[i] != 0
#             O1[i] = round(y[j]; digits = 8)
#             j+=1
#         end
#     end
#     O1=reshape(O1, m,n)
#     O2=ifftshift(O1)
#     O3=ifft(O2)
#     return O1,O2,O3
# end


# Ay = 
# find_Ay(
#     A.Q7_3_1_data_Omega,
#     A.Q7_3_1_data_y
# )

# AAX = 
# find_AAX(
#     A.Q7_3_1_data_Omega,
#     A.Q7_3_1_data_X0
# )

IvMRI (generic function with 1 method)

In [36]:
function find_Ay(Omega, y)
    vec_omega = vec(Omega)
    O1 = complex(Array{Float64}(undef, length(vec_omega)))
    j = 1
    for i in 1:length(vec_omega)
        if vec_omega[i] != 0
            O1[i] = y[j]
            j+=1
        end
    end
    O1 = reshape(O1,512,512)
    O2=ifftshift(O1)
    O3=ifft(O2)

    return O3
end

function find_AAX(X,Omega)
    O1 = fft(X)
    O2 = fftshift(O1)
    O4O3 = Omega .* O2
    O5 = ifftshift(O4O3)
    O6 = ifft(O5)

    return O6
end


function find_grad(X, Omega, y)
    return - find_Ay(Omega, y) + find_AAX(X, Omega)

end

A.Q7_3_1_ans_gradient = 
find_grad(
    A.Q7_3_1_data_X0,
    A.Q7_3_1_data_Omega,
    A.Q7_3_1_data_y
)




512×512 Matrix{ComplexF64}:
  0.0383672+0.760606im    0.686698+0.0784548im  …   -0.813728-0.104892im
     1.5176+0.214358im    0.963876-0.0289204im        2.14156-0.285411im
   0.628935+0.151152im    0.709858+0.0448283im       0.869796-0.205352im
   0.829263+0.217057im     1.27397-0.449533im       -0.426368+0.23571im
   0.540524+0.248817im  -0.0394279+0.123263im       -0.113208+0.10886im
  0.0796532+0.392576im  -0.0891086+0.323551im   …    -0.42816-0.0212641im
    1.43034+0.330078im   -0.738538+0.0774436im      0.0182275+0.0671887im
  -0.111325+0.203347im   -0.298139+0.364208im        0.595705-0.0029911im
  -0.677165-0.215526im   -0.198593-0.127702im       -0.750175-0.0142763im
   0.529782-0.343197im     1.14369-0.369069im        -1.24618+0.136909im
           ⋮                                    ⋱  
   0.131527+0.663346im    0.606727-0.315423im         1.41992+0.388969im
     0.3701+0.495623im    -0.50695+0.117072im       -0.562976+0.0780068im
   0.299432+0.167881im    -1.22638-0.4034

### 2

In [41]:
#NOTE: the wavelet operator is unitary

# #setup for wavelet operators
# function W_normal(X)
#     return dwt(X, wavelet(WT.db4))
# end

# function W_star(X)
#     return idwt(z,  wavelet(WT.db4))
# end

function update_X(X,Omega,y,lambda)
    #Set gamma = n as per required in question
    m,n = size(X)
    gamma = n

    #Here we use the solution found in question 6.2d
    z = X - gamma * find_grad(X,Omega,y)
    a = sign.(dwt(z, wavelet(WT.db4)))
    b = abs.(dwt(z, wavelet(WT.db4))).-(lambda*gamma)
    c = max.(b,0)
    X_new = idwt(a.*c,  wavelet(WT.db4))
    return X_new
end
#test
update_X(
    A.Q7_3_1_data_X0,
    A.Q7_3_1_data_Omega,
    A.Q7_3_1_data_y,
    A.Q7_3_2_data_lambda
)

512×512 Matrix{ComplexF64}:
 -15.6331-248.433im  -222.252-32.3013im  …     273.0+29.0958im
 -667.291-42.8341im  -382.175+13.1423im     -845.508+73.3246im
 -276.242-93.6797im  -299.583+2.07722im     -402.188+90.9603im
 -289.778-54.8916im  -522.193+165.323im      97.5556-116.464im
 -212.819-73.8646im  -62.3687-27.1081im      86.0676-56.4815im
 -30.3421-117.278im   35.9684-66.7953im  …   208.786+36.7204im
 -532.433-114.4im     309.327-58.2398im      56.0559+15.2443im
  44.7583-67.9176im   149.829-101.01im      -172.849+23.7849im
  300.666+109.535im   149.156+61.4936im      306.516+18.1334im
 -200.595+145.943im   -431.86+183.068im      509.794-1.15245im
         ⋮                               ⋱  
 -62.4578-202.031im  -196.162+94.0698im     -611.013-118.178im
 -146.543-135.797im   198.144+20.6114im      181.348-34.8954im
 -91.8455-75.4824im    456.45+143.806im  …   82.1484-171.464im
  266.704-254.333im   223.158-306.82im       64.9094-141.84im
  53.7195-80.7979im   318.102+33.4948im      1

In [ ]:
idwt(_,  wavelet(WT.db4))
dwt(_, wavelet(WT.db4))

In [48]:
# norm(vec(A.Q7_3_1_data_X0),1)
A.Q7_3_2_data_lambda

0.2

### 3

In [63]:
function A_m(x, P_Omega)
    # Apply the 2D Fourier transform
    F_X = fft(x)

    # Apply the FFT shift
    S_F_X = fftshift(F_X)

    # Apply the sampling operator using element-wise multiplication and vectorise
    S_F_X_Omega = vec(P_Omega .* S_F_X)

    nonzeros = filter(x -> x != 0, vec(S_F_X_Omega))

    # Remove the zeroes in the vector
    return nonzeros
end

function PGM(X,Omega,y,lambda)
    X_out = X
    for i in 1:20
        X_out = update_X(X_out,Omega,y,lambda)
        loss = 0.2*norm(dwt(X_out, wavelet(WT.db4)),1)+1/2*norm(y-A_m(X,Omega))^2
        print(loss)
    end
    return X_out
end

PGM(
    A.Q7_3_1_data_X0,
    A.Q7_3_1_data_Omega,
    A.Q7_3_1_data_y,
    A.Q7_3_2_data_lambda
);

#20: 1.88469e52+7.48495e53im
#40: 2.77752e106+1.10308e108im
#100: 8.8902e268+3.5307e270
#1000: 

4.0353440691195625e104.686723022911471e10

3.375222834905798e12

1.7041651420537972e15

8.708078136577242e17

4.449827722053708e20

2.2738619657637078e23

1.1619434645050498e26

5.937531103620809e28

3.0340783939502358e31

1.5504140593085718e34

7.922615843066808e36

4.048456695807143e39

2.0687613715574516e42

1.0571370608658587e45

5.401970381024543e47

2.7604068647035437e50

1.4105679078635124e53

7.208002009182553e55

3.683289026692288e58

512×512 Matrix{ComplexF64}:
  1.88469e52+7.48495e53im  …  -8.08815e53-1.11862e53im
  1.77982e54+1.17821e53im      2.37932e54-3.1391e53im
  7.76138e53+1.9648e53im       1.09801e54-2.36876e53im
  8.78193e53+2.23758e53im       -4.577e53+2.11589e53im
   6.1672e53+2.15052e53im     -2.44386e53+2.06044e53im
   9.6813e52+3.74935e53im  …   -5.4973e53-3.01517e52im
  1.52613e54+2.85431e53im      2.93615e52+4.80071e52im
 -5.86949e52+2.70825e53im      7.05961e53+2.10801e52im
 -8.50659e53-2.44166e53im     -8.10364e53-5.65902e52im
  5.06427e53-4.24256e53im     -1.43329e54+1.17052e53im
            ⋮              ⋱  
   1.4005e53+6.3927e53im       1.68953e54+4.4616e53im
  3.05849e53+4.1873e53im      -6.06748e53+5.67726e52im
   2.6624e53+1.50265e53im  …   -2.6488e53+5.36847e53im
 -7.29432e53+7.4256e53im      -2.43438e53+4.59695e53im
 -1.74921e53+2.8625e53im      -3.60638e53-2.48766e53im
 -2.27154e53+4.91558e53im     -2.28181e53+1.73679e53im
 -3.74864e53-4.11236e52im     -2.39755e53-2.30164e53im
  2.0805

In [ ]:
test1 = A.Q7_3_1_data_X0
test2 = A.Q7_3_1_data_Omega
test3 = A.Q7_3_1_data_y
test4 = A.Q7_3_2_data_lambda

A_m(test1, test2)

## 7.4. MRI CS Recovery: DCT

### 1

In [9]:
dct(A.Q7_4_1_data_X0)

512×512 Matrix{Float64}:
  0.366237     1.19211     1.68995   …  -1.72473     2.93989    0.0413225
  0.191618     0.0864022   0.173086     -0.366286   -0.72923   -0.0877624
 -0.833761    -0.60373    -0.475066     -0.455747    0.171652   1.77861
 -0.00229518  -1.50397     0.260725      0.0783067  -0.457845   0.652336
 -1.3232      -0.192656    1.34458      -0.0999372   1.0288     1.17025
 -0.173484     2.01038    -0.166272  …  -0.987409   -1.46616   -0.609858
 -0.784576     0.167883   -2.01815      -0.8919      0.593913  -1.33394
 -1.34002      0.314492   -0.163357     -1.29248    -0.102672   0.463854
 -0.391789     0.926161    1.04135       1.03238    -0.893262  -1.13684
  0.888325     1.34286    -0.658242     -1.41407    -0.534837  -1.06766
  ⋮                                  ⋱               ⋮         
  1.10533     -0.353828   -0.458405     -0.144269   -0.294954  -0.0169346
  0.884955    -0.0989313  -0.374721     -1.06168    -0.248588   0.10249
 -0.398815    -1.57551     0.95643   …

### 2

## 7.5. MRI CS Recovery: Wavelet and DCT

### 1

### 2